### ISSUE TITLE
db path..오류

### ISSUE THREAD

**Issue by Simhyunjeong16** [jsdevkr/Dumbledore#100]
read me 의 ##installation에 적혀있는 cp./data/dumbledore_sample.db를 bash에서 실행하려고 했으나 이런 오류가 떴습니다..
![db](https://user-images.githubusercontent.com/32221552/31851891-af710a04-b6a9-11e7-981c-2284e09b5e8d.PNG)

**Comment by gimdongwoo** [comment]
MINGW64를 보니 윈도우 인것 같은데요. 윈도우에는 cp 명령이 없죠!

copy던가요? 이제 cp 명령어가 복사 명령이란걸 이해했으나, 탐색기에서 복사해도 됩니다ㅎㅎ
