### ISSUE TITLE
[Question] multiple app management

### ISSUE THREAD

**Issue by ho1234c** [jsdevkr/Dumbledore#103]
프론트부분의 기능을 구상하다보니 multiple app에 대한 부분을 어떻게 해야할지 잘 모르겠습니다. 개념상 여러사람이 bot을 등록하면 parse에 여러 앱이 등록되어야 할텐데 dynamic하게 등록이 가능할까요? 그리고 대시보드도 [parse multiple app](https://github.com/parse-community/parse-dashboard#managing-multiple-apps)를 보면 여러 앱이 한 대시보드에 등록이 가능하긴한데 우리 프로젝트는 dynamic하게 등록이 되어야합니다. 이것에 대한 정보를 찾을수가 없네요.

혹은 여러 앱을 등록하는 방법이 아니라면 만들어진 앱마다의 db를 구분해야하는데 naming 으로 구분하는 것 말고는 어떤방법이 있을까요?

**Comment by wacilpong** [comment]
처음 생각하신 것처럼 다중등록이 우리 프로젝트에 맞는 것 같습니다!! 저도 시간날 때 관련 문서 찾아볼게요. 멘토님은 알고 계실 듯 한데.. ㅎㅎ @gimdongwoo

**Comment by Brew-Brew** [comment]
Live query 안쓰신다고 하신걸보니 다이나믹하게 등록되는것보다는 여러 앱을 등록해놓고 instance 여러개 만들어 사용하는게  맞는것 같아욥!

**Comment by ho1234c** [comment]
저도 서치를 꽤 해봤는데 잘안나오더라구요. 근데 왠지 평범한 방법으로는 안될 것 같다는 생각이 드는게... [오피셜 레포 express 파트](https://github.com/parse-community/parse-server#parse-server--express)에 보면 

> You can also create an instance of Parse Server, and mount it on a new or existing Express website:

mount를 시킨다고 나와 있고, 연동하는 부분 코드를 보더라도

```js
...
// Serve the Parse API on the /parse URL prefix
app.use('/parse', api);
...
```
이렇게 미들웨어를 통해서 parse API를 뚫는데요, 앱이 추가되야하는거면 봇이 추가될때마다 리얼타임으로 앱이 생성되야하는데 express에서 리얼타임에 미들웨어를 등록할 수가 없어요.ㅠ 아마 nodejs에서 불가능한것같네요

**Comment by gimdongwoo** [comment]
개념이 잘못 받아들여진거 같은데요.
parse-server는 한개만 뜨는겁니다.

parse-server는 백엔드 서버 입니다.
parse-server에는 dumbledore라는 앱(서비스)이 하나 등록되어 있습니다.
dumbledore앱(서비스)은 조건에 따라 여러개의 slacbot 인스턴스를 만들고 관리합니다.

**Comment by gimdongwoo** [comment]
개념이 잘못 받아들여진거 같은데요.
parse-server는 한개만 뜨는겁니다.

parse-server는 백엔드 서버 입니다.
parse-server에는 dumbledore라는 앱(서비스)이 하나 등록되어 있습니다.
dumbledore앱(서비스)은 조건에 따라 여러개의 slackbot 인스턴스를 만들고 관리합니다.

slackbot 인스턴스 하나를 카톡에 빗대면 하나의 톡방이나 마찬가지입니다.
여러분 톡방별로 백엔드(혹은DB)를 하나씩 팔겁니까?
아니면 유저별로 백엔드(혹은DB)를 하나씩 팔건가요?

그러니까 dumbledore = 서비스 입니다.
서비스는 하나의 백엔드를, 하나의 백엔드는 하나의 DB를 가집니다.

**Comment by ho1234c** [comment]
앱을 여러개 판다는것 때문에 같은 DB에 앱을 여러개 등록하는걸로 잘못 이해하고 있었네요! Class별로 정보를 모아놓고 가져올 때 앱id 따위를 조건으로 해서 가져오는 형태가 되겠군요.
