### ISSUE TITLE
[Study] Jasmine before 함수

### ISSUE THREAD

**Issue by wacilpong** [jsdevkr/Dumbledore#105]
[학습 -4]
덤블도어 프로젝트는 봇을 구동한 후 메세지를 전달하는 기능이 대부분입니다. 따라서 각 함수들의 테스트코드가 실행되기 전에 먼저 봇을 띄워놓는 테스트코드를 작성하기 위해 `jasmine before`를 공부했습니다. 

1. beforeAll() : describe 내부가 실행되기 전에 한번 실행됩니다. 따라서 이를 봇 메세지를 체크하는 spec describe에 사용하는 것이 좋겠습니다.

2. beforeEach() : describe 내부의 it이 실행되기 전마다 실행됩니다. 

아래의 경우 jasmine 실행 시 a는 1, 2가 찍히며 b는 1만 찍히는 것을 확인할 수 있습니다.

```
describe('sepc', function() {
  let a = 1;
  let b = 1;
  beforeEach(() => {
    console.log(a++);
  });
  beforeAll(() => {
    console.log(b++);
  });

  it(...)
  it(...)
}
```

**Comment by gimdongwoo** [comment]
잘 하고 있어요~
그리고 beforeEach나 before등은 helper를 통해 공통적으로 주입할 수 있습니다.
지금 테스트 코드에도 `helpers/helper.js` 를 보시면 parse-server를 체크해서 인스턴스로 만드는 beforeEach 코드가 있습니다.
