### ISSUE TITLE
[Question] slack에 유저의 메세지 객체

### ISSUE THREAD

**Issue by wacilpong** [jsdevkr/Dumbledore#106]
테스트코드를 작성하려고 보니... 덤블도어는 챗봇이기 때문에 slack에서 유저가 메세지를 보냈을 때, 그 메세지를 슬랙봇에서 구조체화하여 받아오는데요. 그렇다면 이는 테스트코드로 어떻게 구현해야 하는지 감이 잡히지 않습니다. ㅠㅠ

예를 들면, `function awardPoints(originalMessage)`에서 `originalMessag`e는 유저가 slack에 작성한 글과 어떤 채널에 작성했는지 등에 대한 데이터입니다. 이에 대한 테스트코드에서 저 originalMessage 부분은 어떻게 보내야 할까요..? 단순히 String을 보내면 slackBot을 통해 구조화 과정을 거치지 않아서요. 임의로 제가 구조화해서 파라미터로 넘기는 식으로 테스트코드를 작성할 수도 있지만 이건 아닌 것 같아서 ㅠㅠ

혹시 뭔가 아시는 분이 있으면 알려주시면 고맙겠습니다!! 저도 관련 문서를 더 찾아볼게요.

**Comment by gimdongwoo** [comment]
mock이라고 해서, 저 originalMessage를 따라서 만든 객체를 주입해줘서 테스트 합니다.
테스트 코드상에 originalMessage를 만들어두면 되지요.
