### ISSUE TITLE
[학습]React에 대한 학습 올립니다

### ISSUE THREAD

**Issue by songyoungeun** [jsdevkr/Dumbledore#107]
React란 UI를 만드는 자바스크립트 라이브러리로 페이스북이 자사 서비스의 UI를 효율적으로 만들기 위해 만든 라이브러리라 합니다. 
또한 interactive한 UI를 손쉽게 만들기 위해 사용합니다.

특징으로는...

1. UI또는 View를 여러 React Component로 쪼개서 만든다는 것입니다.
component안에 들어가는 코드는 jsx라는 코드로 babel이라는 패키지를 통해 html로 변환되게 됩니다.

2. React는 가상의 DOM을 만들고 변경사항이 있을 때마다 전체가 아닌 해당 부분만 진짜 DOM에 반영하는 방식으로 작업을 수행하여 효율성과 속도를 높입니다.
React가 View를 여러 Component로 쪼갠 이유도 이렇게 DOM을 부분적으로 업데이트할 수 있도록 함입니다.

3. React에선 데이터가 단방향으로 전송되기 때문에 데이터를 추적하기 쉽고 디버깅을 상대적으로 쉽게 된다는 장점이 있고, 이러한 특징을 살려서 Flux 패턴을 사용한 Redux 라이브러리를 많이 활용합니다.

학교에서 배운것들이 조금씩 들어가 있어 반갑기도 했고 그러다가 모르는 내용에서 막히기도 하고 했네요....그래도 우선 react 기초에 대해 많이 찾아보고 공부해 알아가도록 하겠습니다...ㅜㅡㅜ

**Comment by Brew-Brew** [comment]
Codecademy에 간단한 리액트 예제 학습하는 거 있어서 해도 도움 될것같아욥!

**Comment by Brew-Brew** [comment]
인프런에서도 무료강의도 있더라고용

**Comment by LeeYeEun2** [comment]
가서 실습하면서 공부해봐야겟네요 감사합니당👍

**Comment by gimdongwoo** [comment]
네. 잘하고 있습니다.
