### ISSUE TITLE
[화요일 벡엔드 부분 컨트리뷰션 내용 정리]

### ISSUE THREAD

**Issue by Brew-Brew** [jsdevkr/Dumbledore#108]
**- 저번에 멘토님이 말씀해주셨던 내용을 적었었는데 같이 공유하면 좋을 것 같아서 이슈로 남깁니다!**

덤블도어 봇의 벡엔드
 
<서비스 구조>
덤블도어 형태:서비스 (봇 제공 (슬랙))
 
서비스의 user
-슬랙을 운영하는 누군가 (개발자 커뮤니티의 슬랙운영자)
-봇을 원하는 유저의 슬랙 에게 보내줌 (보내주는 것은 bot의 api key, bot의 네임)
 
<bots 클래스>
a KEY,NAME ------->디비 형태로 저장
b ....
c ....
d .....
 
서버가 해야할 일은 이 봇들을 인스턴스로 만들어서 봇들의 FARM을 운영
 
봇이하는일 ->슬랙 메시지에대한 응답
-메시지 저장
-특정 메시지일 경우 ACTION (이 부분은 자연어처리 담당)
 
parse server (모바일 백엔드 as a service)
db에 대한 처리를 알아서 해줌
얘는 전혀 생각할 필요없고, 얘가 꺼내놓은 parse라는 자바스크립트 객체가 있음
parse (javascript sdk)
-query
-object
 
1.parse-server 구동
2.parse상에 있는 봇에 대한 정보 받아오게 바꿔야함.
봇에 대한 정보없이 구동 (현재 코드)
3.bot정보에 대한 entry point 서버에 특정 url을 제공 봇정보를 bots에 계속 업데 이트
리팩토링 해야하는 부분
sqlite3 -> parse js sdk로 바꿔줘야함.
insert ->new parse object
update ->parse query ->parse object
select ->parse query
 
 
1.parse.js sdk
 
2.javascript .promise 문법패턴 비동기처리!
->sqlite를 dependecy에서 없애야함.
 
3.test code
/spec 폴더에 있는 test code

[서비스 사진]
![kakaotalk_photo_2017-10-25-18-19-50](https://user-images.githubusercontent.com/26598542/32010863-ed552ab6-b9ed-11e7-8426-0d82f49d614f.jpeg)
![kakaotalk_photo_2017-10-25-18-19-34](https://user-images.githubusercontent.com/26598542/32010883-fb80c5dc-b9ed-11e7-97c3-8661abddbbe4.jpeg)

잘모르는 부분이 많아 공부해야 할게 많은것 같습니다...!
비동기 처리, promise나 콜백 함수 처리, parse object와 parse query 등등 공부한 내용으로 조금씩 고쳐나갈 예정입니다.
많이 부족해서 여쭤볼테니 많은 능력자분들께서 알려주시면 감사하겠습니당....

**Comment by Brew-Brew** [comment]
http://yubylab.tistory.com/entry/자바스크립트의-콜백함수-이해하기
콜백함수 이해하는데 학습했던 사이트

**Comment by gimdongwoo** [comment]
callback (success, error)
promise
async/await
그리고 테스트 까지 공부하면 됩니다. (할게 많군요!)

**Comment by Brew-Brew** [comment]
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/async_function

async/await promise 이해 도움되는 사이트
