### ISSUE TITLE
봇 채널 설정

### ISSUE THREAD

**Issue by swpark6** [jsdevkr/Dumbledore#11]
https://github.com/kosslab-kr/Dumbledore/blob/796ff641e2f1b6aaf338e64b066baa93a7fddafe/lib/dumbledore.js#L76-L80

각자의 채널에 봇을 추가하실것 같은데, `this.channels[0].name` 은 'general' 채널로 되어있기 때문에 수정이 필요합니다.  
`<botname> say hello to the students` 로 수동으로 호출할 수도 있지만, 별도 파라메터로 받는 코드가 있으면 편할 것 같습니다.
혹은 다른 솔루션이 있는건가요?

제 채널은 `this.channels[3].name` 에 있어서... 일단은 직접 수정해서 사용하고있습니다.

**Comment by gimdongwoo** [comment]
Good!
좋은 캐치입니다. 채널 이름은 알고 있으나 일부러 알려주지 않은 내용입니다ㅎㅎ
`general`이 난리가 나는 모습을 기대하고 있습니다.
