### ISSUE TITLE
[학습] React 학습

### ISSUE THREAD

**Issue by LeeYeEun2** [jsdevkr/Dumbledore#112]
![default](https://user-images.githubusercontent.com/31236688/32113808-62c35acc-bb7c-11e7-9ad4-dc1e07e3bb61.png)
오늘은 codecademy에서 reactjs 에 대해 JSX 요소를 만들고 렌더링하는 법을 배웠습니다! 가장 기본적인 틀이었지만 이렇게 쓰면서 조금씩 해보니 글로 읽는 것보다 훨씬 잘 이해되었습니다.

**Comment by gimdongwoo** [comment]
그런데, 주말에는 공부를 안하는군요! 평일에는 빠짐없이 하시도록 하세요!!
