### ISSUE TITLE
Github policy of counting contribution to forked repo

### ISSUE THREAD

**Issue by wacilpong** [jsdevkr/Dumbledore#113]
컨트리뷰톤 시작하면서 계속 궁금했던 Fork repo의 count관련 규정을 아예 Github staff에 문의해보았습니다. 덤블도어 프로젝트와는 직접적인 관련은 없지만 공유하면 좋은 정보일 것 같아서 이슈남깁니다.

### Q. 1) Forked repository에 하는 push는 contribution counting 될까?
안 된다.  포크로 떠와 나의 프로필에 있는 레포 컨트리뷰션이 올라가는 것은 upstream repo의 default branch로 내가 한 push가 merge됐을 때 뿐이라고 합니다.

### Q. 2) 포크로 떠왔어도 나의 repository로 push한 것을 카운트하고 싶으면 어떻게 하나?
github support 팀에 해당하는 본인의 포크레파지토리 링크를 보내서 public detaching할 수 있게 만들면, 본인의 프로필에서 contribution 카운트가 올라간다고 합니다. 하지만 Pull Request를 보냈을 때 원래는 자동으로 본인이 포크한 레파지토리에 push하는 내용들이 올라가는데, 이것이 안된다고 합니다. (you will lose the ability to easily contribute your commits back upstream)

따라서 이러한 방법을 쓰거나, 포크로 떠오지말고 standalone repository로 만들어서 push하면 본인의 프로필 카운팅이 될 것입니다. 하지만 PR했을 때 자동반영되는 기능은 포기해야 하는 것 같으니, 저는 그냥 냅두려고요... ㅋㅋ 계속 관련 깃허브 정책이 궁금했는데 이렇게 알게되니 속시원하네요!

**Comment by gimdongwoo** [comment]
오! 문의를 보내는 진취적인 자세와 상세한 정리 좋네요.
그러니 1번의 내용대로 PR을 많이 보내야 합니다. 그리고 merge되면 과거의 빈칸이 채워지죠!!
