### ISSUE TITLE
eslintrc 관련 오류

### ISSUE THREAD

**Issue by Brew-Brew** [jsdevkr/Dumbledore#114]
<img width="572" alt="2017-10-28 9 37 05" src="https://user-images.githubusercontent.com/26598542/32134422-3702df0a-bc28-11e7-9128-b84df7810abb.png">

새로 eslint관련해서 추가된것 때문에 생긴 오류인것 같은데
Atom core package 에서는 LF로(?) 기존에 설정되어있는 것을
npm run lint -- --fix 입력한 후 실행하시면
정상적으로 실행됩니다!!

**Comment by Brew-Brew** [comment]
참고주소 https://github.com/diegohaz/arc/issues/171

**Comment by ho1234c** [comment]
https://github.com/kosslab-kr/Dumbledore/blob/d1c445cf7f4a97823865bfa9817ddf181911c4c3/package.json#L12

fix는 자주쓰는 기능이라 우리 프로젝트 스크립트에도 추가되어있습니다!

**Comment by Brew-Brew** [comment]
<img width="1182" alt="2017-10-29 8 52 27" src="https://user-images.githubusercontent.com/26598542/32143337-316934b8-bceb-11e7-926c-9181d9f37880.png">
해결된줄 알았는데 해결이 안되었네요 ㅠ...
다시 클론떠서 다시 실행해보는데, Expected linebreaks to be 'CRLF' but found 'LF' 라는 에러가 계속 뜨는데 eslint가 제대로 적용이 안되서 그런건가요? ㅜㅜ.... 다른파일의 line break style? 이 다 LF로 되어있고 page 폴더의 index.js 파일은 CRLF로 되어있긴한데 npm run dev로 실행하니 노란색으로 변경되었다는 표시가 뜨네요 ㅠ..

**Comment by Brew-Brew** [comment]
<img width="1185" alt="2017-10-29 8 58 59" src="https://user-images.githubusercontent.com/26598542/32143404-0b73d62c-bcec-11e7-9fd0-8ab34806bf37.png">
npm run lint -- --fix  명령어로 오류는 없어지는데 위와같이 노란색으로 표시되면서 변경되었다고 나와서요 ㅠ..

**Comment by gimdongwoo** [comment]
윈도우에 CRLF를 허용했더니 그게 그대로 커밋되어 문제군요-_ -;
아오 빌어먹을 윈도우......
lf만 허용하는 원래의 룰로 변경해야겠습니다.

**Comment by gimdongwoo** [comment]
windows 사용자는 각 에디터 별로 개행문자를 \r\n이 아니라 \n 으로 처리하는 옵션을 찾아서 사용해주시기 바랍니다.

vscode에서는
Add "files.eol": "\n" to your settings file.
