### ISSUE TITLE
function 질문 드립니다..

### ISSUE THREAD

**Issue by HyeonUkCho** [jsdevkr/Dumbledore#116]
![image](https://user-images.githubusercontent.com/18049575/32171627-1bf0eb7c-bdbc-11e7-848b-aa6c344a6e68.png)

이렇게 모듈로 만들어서 bot.js에서

![image](https://user-images.githubusercontent.com/18049575/32171640-28c09f00-bdbc-11e7-9232-a6a1f58e9237.png)

이렇게 호출하려는데 postRequest가 function이 아니라고...하는데 왜 이럴까요,,,
너무 기초적인거를 질문드려서 죄송합니다...

**Comment by gimdongwoo** [comment]
이렇게 봐서는 뭐가 문제인지 인지가 잘 안되는데요.

그리고, 코드를 올린땐 캡쳐하지 말고 코드 상태로 올려줘요ㅎㅎ

그리고 전후 맥락에 문제가 있을 수 있으니, 풀코드로 올려야하구요.
