### ISSUE TITLE
[학습] React 학습2

### ISSUE THREAD

**Issue by Simhyunjeong16** [jsdevkr/Dumbledore#117]
<img width="960" alt="s" src="https://user-images.githubusercontent.com/32221552/32183810-a5065cc8-bddd-11e7-9413-b8c1b368e1a5.png">

Codecademy에서 react에 대해서 좀더 세부적으로 공부를 했습니다.

* map 메소드 : 배열에서 활용할 수 있는 메소드입니다.
함수를 인자로 받아서 배열의 각 값과 함수가 동작한 결과를 새로운 배열에 담아주는 기능을 합니다.

* key 속성 : JSX의 속성으로 React가 내부적으로 활용하는 속성입니다. 이 key를 이용해서 list를 추척합니다. 리스트의 순서가 뒤섞였을 때, 리스트 아이템이 한 렌더링에서 다른 렌더링으로 가지고 가는 메모리가 있을 때 key 속성을 사용합니다.

**Comment by gimdongwoo** [comment]
더더 열심히 하세요~
