### ISSUE TITLE
[질문]bot 클래스 생성

### ISSUE THREAD

**Issue by Brew-Brew** [jsdevkr/Dumbledore#119]
지금 현재는 parse server에 info user role 이라는 클래스만 만들어지고 있고,
현재 방식은 사용자가 환경변수를 설정해서 임의의 봇api key와 봇 이름을 지정해준다음 시작하는 방식인데요! 이제 봇정보를 받아와서 인스턴스를 뿌려주려면 여러개의 봇들의 api key와 이름이 들어가있는 클래스가 만들어져야 할텐데요!! 

[봇 클래스]
이름    api key
bot1    ------
bot2    ------
bot3    ------

이런식으로 구성된 여러 봇정보가 있는 클래스를 추가하는 과정을 거쳐야할텐데  제가 생각해본것은 여러봇의 정보가 들어있는 모듈을 하나 만들고 이모듈에서 정보를 가져와서 봇클래스(object) 에 저장하는 방식을 생각했는데 
이렇게 만드는과정에서 봇의 api key 가 그대로 코드상에 들어가도 되는지 궁금해서 여쭤봅니다!!ㅠㅠ

(제가 생각한 방식이 맞는지도 여쭤봅니댱..)

**Comment by gimdongwoo** [comment]
봇 클래스에 유저의 봇 정보가 저장되는 것은 맞습니다.

그리고 봇을 만드는 것은 테스트 코드로 만들어야하고, 테스트 코드상에는 API Key가 포함되어도 됩니다.

그런데 슬랙이 모든 github 리파지터리를 감시하고 있다가 API Key가 퍼블릭하게 올라오면 해당 봇의 API Key를 Revoke해버리거든요.

그래서 base64인코딩해서 저장해놨습니다.
https://github.com/kosslab-kr/Dumbledore/blob/97a86718cea7d2a07ec6288bb88cf0fa559b6601/.travis.yml#L12

https://github.com/kosslab-kr/Dumbledore/blob/97a86718cea7d2a07ec6288bb88cf0fa559b6601/bin/bot.js#L36

유사하게 테스트 코드에 미리 parse에 부을 테스트 데이터를 준비해서 이걸 개발 단계에도 쓰고 테스트에도 쓰고 그러면 됩니다.
