### ISSUE TITLE
[질문사항] id undefined 뜨는데 설정을 어떻게 해야하나요?

### ISSUE THREAD

**Issue by HyeonUkCho** [jsdevkr/Dumbledore#12]
![image](https://user-images.githubusercontent.com/18049575/30998234-ffa3ec34-a507-11e7-9ef5-84f00a463dda.png)

**Comment by gimdongwoo** [comment]
질문을 남길때는 실행한 커맨드부터 과정을 상세하게 알려주셔야 해결할 수 있습니다.

다시다시~

**Comment by swpark6** [comment]
https://github.com/kosslab-kr/Dumbledore/blob/796ff641e2f1b6aaf338e64b066baa93a7fddafe/lib/dumbledore.js#L10-L14

부분에서 line 12 의 dumbledore 부분을 자신이 추가한 슬랙봇 이름으로 바꾸시면 됩니다.

저같은 경우는 sewon-bot 으로 해두었는데, 이경우에는 
this.settings.name = this.settings.name || 'sewon-bot'; 
으로 하였습니다.

p.s
네임기준으로 id를 파싱하게 되어있는데 덤블도어라는 이름으로 봇을 추가하신게 아니라서 id에 값이 들어가지 않게 됩니다.
(추가) 잠깐 이슈가 올라오자마자 지워진 것을 보고 힌트를 얻었네요.. 저 코드페이지보단 위에 bot.js에서 수정하시는게 더욱 일반적일것 같네요.. [사실 BOT_NAME env를 주면 되지만요]

**Comment by lastindus** [comment]
![image](https://user-images.githubusercontent.com/18049575/30998298-7f323e74-a508-11e7-912a-ad5702c7ce60.png)

**Comment by HyeonUkCho** [comment]
`======================================
//dumbledore.js
var Dumbledore = function Constructor(settings) {
    this.settings = settings;
    this.settings.name = this.settings.name || 'ddb_hyeonwook';
    this.dbPath = settings.dbPath || path.resolve(process.cwd(), 'data', 'dumbledore.db');
    this.githubChannel = settings.githubChannel || 'null';

    this.user = null;
    this.db = null;
    this.params = {
      link_names: 1
    };
};

=========
//bot.js
var token = 'slack_token';
var dbPath = '../data/dumbledore.db';
var name = 'ddb_hyeonwook';
var githubChannel = '#hyunwook';

var dumbledore = new Dumbledore({
    token: token,
    dbPath: dbPath,
    name: name,
    githubChannel: githubChannel
});

dumbledore.run();
`
이렇게 설정하고 실행 후,
제가 만든 채널에서 '@ddb_hyeonwook say hello to the student'으로 입력한 후 위와 같은 에러가 떴습니다.
어떤 부분이 잘못된걸까요;;

**Comment by swpark6** [comment]
일단 명령은 @<bot-name> 에서는 동작하는것이아니라 <bot-name>에서 동작합니다.
`ddb_hyeonwook say hello to the student` 로 테스트하셔야 될것같습니다.

https://github.com/kosslab-kr/Dumbledore/blob/796ff641e2f1b6aaf338e64b066baa93a7fddafe/lib/dumbledore.js#L40-L44

에서 user가 세팅되는데, 일치하는 name이 없다면 오류가 납니다.

혹시 오타가 있는지 조심스럽게 여쭤봅니다...

**Comment by HyeonUkCho** [comment]
아....오타가 있었습니다 감사합니다

**Comment by gimdongwoo** [comment]
좋아요~ 좋아 이렇게 해결해나가는거죠.

덤블도어 교수님, @swpark6 에게 1점 주세요!
