### ISSUE TITLE
react학습1031

### ISSUE THREAD

**Issue by songyoungeun** [jsdevkr/Dumbledore#120]
![dms](https://user-images.githubusercontent.com/32218545/32228513-c6a581a6-be91-11e7-8d81-6facd4c55daa.jpg)

오늘의 학습일지입니다!!
지금까지 리엑트 배운 것과 여러 정보들을 찾아보며 리엑트 창을 만들어보고 있습니다..! 얼른 완성되는데로 올려보도록 하겠습니다!
그리고 이번주는 참석하지 못하였지만  다음주는 갈 수 있을 거 같습니다!!

**Comment by ho1234c** [comment]
제가 그전까지 러프하게 컴포넌트 잡아놓을게요~

**Comment by gimdongwoo** [comment]
굿!
