### ISSUE TITLE
[Question] NODE_ENV가 development일 때 목업데이터

### ISSUE THREAD

**Issue by wacilpong** [jsdevkr/Dumbledore#124]
저번 컨트리뷰션 때 멘토님께서 말씀하셨던 bot에 대한 목업데이터를 slackBot의 토큰과 이름 정보라고 이해했는데 맞나요?

그래서 데이터를 심은 봇을 parse server가 올라간 후에 dumbledore가 생성되기 전에 만들어서 dumbledore 클래스로 넘기려고 합니다.

혹시 목업데이터를 심는다는 의미를 잘못 파악한지 의문이어서 일단 이슈 남깁니다..!

**Comment by ho1234c** [comment]
더미데이터를 넣으라는 말씀이 아니셨을까요? mongodb-runner속에 데이터가 temporary하기때문에 parse-server가 재시작될때마다 데이터가 날아갑니다. 그러면 front테스트를 위해서 킬때마다 데이터를 수동으로 입력해줘야하는데 목업데이터를 넣는 코드를 추가하면 그런 수고를 할 필요가 없어지니깐요. 

맞다면 db에 직접 수동으로 넣어줘도 되고 목업이벤트를 만들어서 발생시켜줘도 될것같네요!

**Comment by Brew-Brew** [comment]
Node env가 development일때는 봇 이름 봇api 키를 포함한 목업데이터를 일단은 parse server가 시작하기전 만들어  뿌려준다고 저도 생각하고있었어욥  ㅠ

현재는 임의의 env 설정으로 봇이구동되는데 node env가 product일때는 이제 parse server에서 봇클래스를 인스턴스화해서 api 키와 봇 이름을 받아와 구동하는 봇crud 하는 코드가 필요하다고 생각하고 있어욥! 그리고 이런것들을 manage하는코드도 필요하고용! 제가생각한게 맞나용 ...ㅎ

**Comment by gimdongwoo** [comment]
@ho1234c 님과 @zx6658 님이 맞게 찾아가고 있어요.

(공통) parse-server시작
(development) 테스트-개발용 Bot데이터를 parse에 저장
(공통) parse 로부터 Bot데이터를 가지고 와서 그 갯수만큼 Dumbledore 생성

**Comment by wacilpong** [comment]
음.... 뭔가 제가 질문을 애매하게 남긴 것 같아요. 그러니까 제가 궁금한 것은 그 목업데이터가 bot정보를 의미하는 것이 맞는지가 궁금한 거였어요. 슬랙봇이 넘기는 메세지 구조까지 목업으로 심어야 하는건지, 그래야 한다면 어떻게 해야하는 건지 궁금해서ㅎㅎ 아무튼 답변주신대로 알고 있을게요! 고맙습니다~

**Comment by gimdongwoo** [comment]
맞아요. Bot데이터죠.
Bot을 만들기 위한 API키와 이름이요.
