### ISSUE TITLE
[자연어처리] 진행 상황 공유

### ISSUE THREAD

**Issue by HyeonUkCho** [jsdevkr/Dumbledore#128]
<자연어 처리 outline>
기존 명령어 이외의 문장이 입력이 되었을 때 apiai로 문장을 보내어 문장에 대한 intent를 파악하고 그에 해당하는 답을 받아 봇이 대답을 할 수 있도록 만드려고 하고 있습니다.

<현재 진행 사항>
기존 명령어 이외의 문장이 입력 되었을 때 apiai로 보내고 받는 부분을 확인하였습니다. 하지만 이 과정에서 채팅창에 display하는 부분에서 어려움을 겪고 있습니다.

<앞으로의 계획>
apiai와의 통신 과정이 문제없이 동작하는 부분까지 완료한다면
첫째, 기존 명령어가 정확한 문장이 아니더라도 기능이 동작이 가능하도록 구현해보겠습니다.
둘째, 기능 관련 명령어 이외에의 경우도 고려하여 적절한 답을 할 수 있도록 구현해보겠습니다.

자연어 처리 관련하여  궁금하신 점이 있으시다면 언제든지 글을 남겨주시기 바랍니다.

**Comment by gimdongwoo** [comment]
화이팅입니다~ 열심히 해서 인터뷰 하실때 내가 이런것도 해봤다고 자신있게 말할 수 있는 케이스가 되면 좋겠네요.
