### ISSUE TITLE
indexOf(jasons's mom) 인식

### ISSUE THREAD

**Issue by swpark6** [jsdevkr/Dumbledore#13]
https://github.com/kosslab-kr/Dumbledore/blob/796ff641e2f1b6aaf338e64b066baa93a7fddafe/lib/dumbledore.js#L259-L260

jasons's mom 이 제대로 파싱이 안되는것 같습니다.
일단.. 어떤 기능인지는 잘 모르겠지만, 중요한 기능은 아닌거 같습니다.
' 때문에 그런것 같은데 추후에도 ' 를 사용할 때가 되면 같은 이슈가 생길것 같아 올려봅니다.

**Comment by gimdongwoo** [comment]
`\`는 자바스크립트의 escape문자죠. 코드상으로는 문제가 없어보이는 부분인데요.
tell me about jasons's mom이 동작하지 않는것인가요?

물론 저 부분이 dictionary로 되어 있지 않고 if문 반복으로 되어 있는 것은 문제지요.

**Comment by swpark6** [comment]
indexOf('jasons mom') 으로 바꾸었을 시 동작이 잘 되지만, \'  를 추가하는 순간 명령어가 시행되지 않습니다. [직접 타이핑 및 여러 경우도 시도해보았으나... 시행되지 않습니다.
![image](https://user-images.githubusercontent.com/14174350/30998542-5921692e-a50a-11e7-8d05-00ed0b49b0b0.png)

![image](https://user-images.githubusercontent.com/14174350/30998555-80d87840-a50a-11e7-9f83-e25f4cf0c942.png)

**Comment by ho1234c** [comment]
![image](https://user-images.githubusercontent.com/11595293/31006435-9f4b950a-a537-11e7-9cc8-200f9081ea36.png)

저는 잘 되는것 같은데... 개발환경이 어떻게 되시나요?

**Comment by swpark6** [comment]
OS X 입니다.. 혹시 "jason's mom" 텍스트로 붙여넣어주실 수 있나요? 복사 해볼게요..

**Comment by ho1234c** [comment]
ho1234c-bot tell me about jason's mom

아 저는 윈도우10이에요

**Comment by ho1234c** [comment]
그런데 위의 이미지만 보더라도 single quote 종류가 달라보이네요.
https://www.thoughtco.com/typing-quotes-apostrophes-and-primes-1074104 이글 참조해보니 
Straight single apostrophe랑 Opening single apostrophe의 차이인거같아요.

**Comment by swpark6** [comment]
![image](https://user-images.githubusercontent.com/14174350/31007099-4b1eb360-a53a-11e7-9313-94b213dd8a88.png)
덕분에 해결했습니다.

MAC 인 경우 아주 스마트(?) 하게 쿼터를 바꿔주는 덕분에 생긴 이슈네요...
스마트 인용 및 대시 사용 체크해제 혹은 작은따옴표 에서 적절한 모양으로 바꾸면 되는것 같습니다.

![image](https://user-images.githubusercontent.com/14174350/31007125-62ae83de-a53a-11e7-8024-0226d9e9341c.png)

코드는 매우 정상인걸로!

**Comment by ho1234c** [comment]
그런데 싱글쿼트는 개발할 때 안쓸수가 없는 문자인데 지금까지 개발하실 때 이슈가 없었나보네요.
협업에서 항상 모두가 맥을 사용하셨다던가..?

**Comment by swpark6** [comment]
ㅋㅋ 그러네요.. 기억은 안나지만 많이 사용한것같은데 아마 정적으로 ' 를 넣어두고 비교하거나, 데이터 처리할 때 사용을 한 적은 없어서 그런것 같습니다.

**Comment by ho1234c** [comment]
아마 맥이랑 윈도간에 CRLF 이슈도 있을 수 있다고 알고있는데... 문제생기면 그때 가서 대응하면 될것같습니다.
