### ISSUE TITLE
1104 REACT 학습

### ISSUE THREAD

**Issue by songyoungeun** [jsdevkr/Dumbledore#130]
![1104](https://user-images.githubusercontent.com/32218545/32388174-313138f6-c10a-11e7-8f3e-ff0d9fa90937.PNG)

       \^~^/학습완료~@~@

**Comment by gimdongwoo** [comment]
좋습니다~ 직접적인 컨트리뷰션은 이번엔 무리라도 React를 배워두는게 큰 도움이 될거에요~
