### ISSUE TITLE
[이슈] 유저(student)의 목업데이터

### ISSUE THREAD

**Issue by Brew-Brew** [jsdevkr/Dumbledore#132]
**[진행한 것]**
awardPoint 부분을 수정하였습니다. 
현재 [10 points to @user] 와 같은 명령어로 parse server에서 @user 에 해당하는 userId를 student 클래스에서 매칭 시켜 그 학생에게 점수를 주게 수정해놓았습니다. @swpark6 님의 reaction이 일어났을때 점수가 올라가는 함수를 짜놓으신걸 덜건드리기위해 그대로 인자세개를 받는 형식으로 수정하였습니다!

tellmeabout 함수에서 메시지가 안나왔던것을 수정하였습니다. [tell me about @user] 와 같은 명령어로 student클래스에서 @user에 해당하는 userId를 매칭시켜 그 학생의 포인트를 알려줍니다.  포인트는 제대로 나오는데, convertToUserName 함수를 이용해서 유저의 이름으로 변환하는것은 계속 하고있습니당

**[이슈]**
@wacilpong  님께서 봇 목업데이터를 development환경일때 parse server가 시작하기전에 봇클래스로 저장하는 pr을 올려주신것 같아서, 봇목업데이터 말고도 덤블도어봇을 사용하는 슬랙의 user(student) 리스트를 받아와서 student클래스에 그 슬랙에 있는 모든 student를 클래스에 추가해주는 목업데이터도 필요할것 같습니다!

슬랙 채팅창에서 여러 명령어를 입력하여 parse-server에 있는 student 클래스에 있는 학생들의 포인트를 업데이트 해주거나, 학생들의 점수를 불러오거나 등등의 명령어들을 활용하기 위해 이런 학생들(즉, 슬랙채널내 user들)의 목업데이터가 들어가야할것 같습니당!

**(+질문)** 
tellmeabout 함수를 수정하다가 질문이 생겼는데욥!
 convertToUserName 함수 실행과정에서 await this.slackBot.getUsers() 부분에 getUsers 부분이
Cannot read property 'getUsers' of undefined와 같이 나오는데 이유가 있을까용..ㅜ 

아그리고 points from과 같은 명령어로 유저의 점수를 깎는 명령어가 있었는데 별로 필요없어보여서 ..없애는게 낫겟죵?

**Comment by ho1234c** [comment]
말씀해주신대로 프론트파트 작업에서도 봇 목록, 각 봇의 student목록과 그 student에 부여된 포인트에 대한 목업데이터가 필요합니다. 지금은 임시로 프론트에서 더미데이터를 객체 리터럴하게 만들어서 사용하고있어요.

그리고 돌려보지는 않았지만 코드만 봤을 때는 convertToUserName를 호출할 때 this를 바인딩해주고 있지않아서 this에 slackBot객체가 없을 것 같습니다. 당연히 그 속의 getUsers도 undefined일거구요. 얼마전에도 이슈에 있었던 것과 같은 문제인데요, lexical scoping과 관련된 이슈입니다. 일반적인 호출에 있어서 convertToUserName속의 this는 전역객체입니다. 그리고 추가적으로 convertToUserName가 async function인데 동기코드처럼 사용되고있네요. await키워드도 추가되어야 할 것같아요.

```js
...
const userName = await convertToUserName.call(this, student);

if (userName !== 'dumbledore') {
...
}
...
```

과 같은식으로 되어야겠네요.

**Comment by Brew-Brew** [comment]
아아 그렇군용..! 감사합니다!! student목업 데이터 부분 수정 얼른 해보겠습니다!
바인딩 개념이 아직 익숙치 않아서 ㅠ 바인딩하는 부분이랑 async function인데 동기코드처럼 사용되는 다른부분역시도 찾아서 수정해보도록 하겠습니다!! 계속 여쭤보도록 하겠습니당..감사함댜..

**Comment by wacilpong** [comment]
짱짱...
