### ISSUE TITLE
[help wanted] 발표자료 흐름

### ISSUE THREAD

**Issue by wacilpong** [jsdevkr/Dumbledore#133]
@thomasJang 부멘토님의 자료를 참고하여 발표자료의 컨셉과 흐름을 아래와 같이 정리했습니다. 그리고 일단은 파워포인트로 자료를 만들 생각입니다... 디자인이나 이벤트 입히는 부분이 제가 더 수월해서... ㅎㅎ.. 혹시 Prezi로 만들고 싶거나 다른 아이디어 있으시면 꼭꼭 말씀해주세요 여러분 함께 만들어요..!

```
호그와트 학교 컨셉, 멘토교장선생님과 아이들

1. 덤블도어 교수님이란?
2. 공헌도 / 프론트 / 백엔드 / 테스트 & CI (각각이 한 일 보여줌)
3. 우리가 모인 나날들 (사진이랑 같이)
4. 얼마나 참여했나요? (발표 전날까지의 이슈 및 PR 개수와 contributor 그래프 보여줌)
5. 덤블도어봇 띄워서 테스트하는 영상
```

**Comment by ho1234c** [comment]
작년 기억을 더듬어보면... 특이하게 발표하는 팀을 제외하면 거의 본인 팀말고는 다들 딴짓하던거 같았어요. ㅋㅋ 2번은 지루할수 있으니 최소한으로 하는게 좋을것 같고, 컨셉이 꽤 재밌는 편이니까 관련 이미지랑 같이 강조하면 좋을거라고 생각합니다! 그리고 챗봇이다보니 시연도 재미없을것 같은데 잘 보여줄수 있는 방법을 생각해봐야겠네요.

**Comment by thomasJang** [comment]
제 개인적인 생각으론 
이야기에 집중할 수 있게 스토리텔링 방식이 좋을 것 같습니다.

챗봇이란 주제에 접근하는 과정 팀원들과의 이야기들 만들어진 것 들 그리고 후기.

**Comment by gimdongwoo** [comment]
그런데 팀장님들 제가 리파지터리에 Write 권한드려서, 이슈에 라벨 달 수 있지 않나요?

**Comment by thomasJang** [comment]
그냥 만든 작품 소개하면 무조건 망합니다.

**Comment by wacilpong** [comment]
안그래도 1일1이슈같은 규칙들을 우리가 잘 지킨 것 같아서 이런 숫자들로 스토리텔링을 만들어보려고 했는데 좀더 고민해봐야겠습니다.
