### ISSUE TITLE
[이슈] 학생 목업데이터

### ISSUE THREAD

**Issue by Brew-Brew** [jsdevkr/Dumbledore#137]
현재 덤블도어봇 시작시, 학생테이블에 학생데이터가 없을경우 슬랙봇을 추가한 슬랙의 모든 유저의 데이터를 가져와서, 변환해 목업데이터를 만들어 클래스에 저장시키는것 까지는 구현한 상태입니다. 그런데, 아래와 같이
<img width="1439" alt="2017-11-07 1 01 48" src="https://user-images.githubusercontent.com/26598542/32476673-1f7b0290-c3bc-11e7-951c-edb101e3fe93.png">

일반 유저가아닌 bot들과 같은 것도 역시 유저로 인식되기 때문에, 유저로 잡혀 약 35개?정도의 유저가 학생테이블의 목업데이터로 저장되게 되는데, 일반 유저만 필터링할 좋은 방법이 있을까용..?

**Comment by gimdongwoo** [comment]
봇도 유저라고 생각하고 그냥 하세요ㅎㅎ

**Comment by Brew-Brew** [comment]
아 그리고 저 botid는 일단은 userid로 임시로 넣었습니당

**Comment by Brew-Brew** [comment]
아 그러면 되나용?

**Comment by ho1234c** [comment]
봇 이름으로 구분하면 되지않나요?

**Comment by wacilpong** [comment]
Parse 올라갈 때 Bot 오브젝트에 봇들을 저장하니까 이걸 가져와서 체크하면 안되려나요?

**Comment by Brew-Brew** [comment]
봇은 profile 속성에 일반유저와 다르게 botid라는 속성이 있더라규용 그래서 그속성이 있으면 걸러서 체크할 예정입니당

**Comment by Brew-Brew** [comment]
해결하여 다시커밋했습니당!
