### ISSUE TITLE
[help wanted] PR merge 권한

### ISSUE THREAD

**Issue by wacilpong** [jsdevkr/Dumbledore#140]
아주 간단한 PR들을 보내면 바로 커밋 머지하고 싶은데 권한이 없습니다.. ㅠㅠ 메일에서 체크하라고 하셨는데 메일에 아무것도 오지 않아서요.. 스팸함에도 없어서, 다시 한번 확인해주시면 고맙겠습니다!

**Comment by gimdongwoo** [comment]
Team 권한으로 안되는거 같아서, collaborator에 등록했습니다.
이메일이 갔을거에요~
<img width="736" alt="2017-11-08 11 29 18" src="https://user-images.githubusercontent.com/7310854/32554328-c7079cdc-c4dc-11e7-9d44-df0e8e6d03c2.png">
