### ISSUE TITLE
Travis - heroku Deploy 연동

### ISSUE THREAD

**Issue by gimdongwoo** [jsdevkr/Dumbledore#145]
[목적하는 CI 프로세스]
1. master branch에 추가된 commit이 travis에서 build와 test가 성공했을 때
2. heroku로 deploy 하여 서비스를 돌린다.

[준비물]
1. heroku 계정과 api key
2. mongodb atlas의 db instance (영속적 데이터 저장을 위함)

[셋업]
1. travis에 heroku 처리를 추가함
> https://docs.travis-ci.com/user/deployment/heroku/
2. heroku에 app을 만듬
> https://dashboard.heroku.com/apps/

[새행착오]
1. heroku에 PORT 설정
> 헤로쿠는 외부로 노출되는 포트를 1개만 지원함
> process.env.PORT를 받아서 사용해야함 (heroku 자체에서 port를 제공함)
> `bin/bot.js`에 webServer 만드는 부분에 엉뚱한 설정 있었음...
> parse api용 마운트 포인트를 `http-proxy`를 이용하여 잡음
> parse : https://dumbledorebot.herokuapp.com/api/parse

2. devdependencies 
> webpack 빌드를 하기 위해서는 devdependencies의 설치가 필요함
> https://devcenter.heroku.com/articles/nodejs-support#devdependencies
> `package.json`에 `"postinstall": "npm run build"` 추가

3. static file serving
> `server/app.js`에 static 파일에 대한 마운트가 없었음. 그래서 `dist/bundle.js` 접근불가
> app.use(express.static(path.join(__dirname, '..', 'public')));

4. heroku log 보기
> heroku log 메뉴를 못 찾아서 한참 해맴
<img width="215" alt="2017-11-10 1 17 57" src="https://user-images.githubusercontent.com/7310854/32642742-b1396f8c-c619-11e7-9a51-3cfd85700638.png">

[최종결과물]
https://dumbledorebot.herokuapp.com/

**Comment by gimdongwoo** [comment]
@wacilpong @ho1234c 보시오~

**Comment by ho1234c** [comment]
postinstall로 travis에서 빌드해서 헤로쿠로 던지는거져?

**Comment by gimdongwoo** [comment]
@ho1234c heroku로 git의 HEAD를 던지는거라 travis에서 빌드한거랑 별개로 heroku에서 다시 빌드해야되더군요.

**Comment by wacilpong** [comment]
와 진짜 문서와 구글이 없었으면 힘들었을 것 같아요... 넘 수고하셨습니닷 커밋내역 확인하면서 공부핳겠습니다~!

**Comment by ho1234c** [comment]
@gimdongwoo 그럼 지금 링크에서 처럼 헤로쿠 production mode가 꺼져있는거군요

**Comment by Brew-Brew** [comment]
와우 저도 리액트 잘쓰고싶어요..
