### ISSUE TITLE
봇 설정 질문

### ISSUE THREAD

**Issue by HyeonUkCho** [jsdevkr/Dumbledore#15]
======================================
//dumbledore.js
var Dumbledore = function Constructor(settings) {
this.settings = settings;
this.settings.name = this.settings.name || 'ddb_hyeonwook';
this.dbPath = settings.dbPath || path.resolve(process.cwd(), 'data', 'dumbledore.db');
this.githubChannel = settings.githubChannel || 'null';

this.user = null;
this.db = null;
this.params = {
  link_names: 1
};
};

=========
//bot.js
var token = 'slack_token';
var dbPath = '../data/dumbledore.db';
var name = 'ddb_hyeonwook';
var githubChannel = '#hyunwook';

var dumbledore = new Dumbledore({
token: token,
dbPath: dbPath,
name: name,
githubChannel: githubChannel
});

dumbledore.run();

==========================================
이렇게 설정하고 실행 후,
제가 만든 채널에서 '@ddb_hyeonwook say hello to the student'으로 입력한 후 아래와 같은 에러가 떴습니다. 어떤 부분이 잘못된걸까요;;

![image](https://user-images.githubusercontent.com/18049575/30998645-35ee5772-a50b-11e7-854a-e8de1d02b4b2.png)

**Comment by ho1234c** [comment]
close #12
