### ISSUE TITLE
[parse dashboard] parse dashboard error 

### ISSUE THREAD

**Issue by Brew-Brew** [jsdevkr/Dumbledore#150]
<img width="1081" alt="2017-11-11 1 52 47" src="https://user-images.githubusercontent.com/26598542/32669259-383e714e-c683-11e7-8aaf-e378f7198b24.png">
새롭게 merge된 것들을 받고 서버는 정상적으로 켜졌는데 기존에 로컬에서 개발테스트를위해 서버를 켯을때 나오던 parse dashboard가 안뜨네용ㅠㅠ

**Comment by gimdongwoo** [comment]
안뜨는건 당연합니다. 코드가 뭐가 바뀌었는지 봤으면 눈치 챘을텐데...
파스 서버(1337)에서 웹서버(55555) 쪽으로 dashboard를 옮긴겁니다.
