### ISSUE TITLE
reply in thread

### ISSUE THREAD

**Issue by ho1234c** [jsdevkr/Dumbledore#158]
그동안 백엔드부분에 잘 참여하지 못해서 이제야 발전된 코드를 봤는데요ㅠ 지금 점수를 부여하는 시스템이 thread로 달린 답변이냐를 판별해서 점수를 주고 있는것같습니다. 그런데 그럴필요가 있는건지 모르겠습니다.

테스트해보니 thread에서 답변을 하는 경우 두가지 이벤트가 발생합니다.
```js
// plain chat message 이벤트
{ type: 'message',
  channel: 'C7CJEP90X',
  user: 'U7BAHGS5D',
  text: '테스트',
  ts: '1510463009.000073',
  source_team: 'T7B8QKJ8P',
  team: 'T7B8QKJ8P',
  thread_ts: '1510461580.000041' }
```

```js
// root message의 thread에 새로운 message가 만들어짐으로 인해 발생하는 이벤트.
{ type: 'message',
  user: 'U7BAHGS5D',
  text: 'dd',
  thread_ts: '1510461580.000041',
  reply_count: 4,
  replies:
   [ { user: 'U7BAHGS5D', ts: '1510461871.000015' },
     { user: 'U7BAHGS5D', ts: '1510461895.000041' },
     { user: 'U7BAHGS5D', ts: '1510462514.000054' },
     { user: 'U7BAHGS5D', ts: '1510462825.000003' } ],
  unread_count: 4,
  ts: '1510461580.000041' }
```

보통 커뮤니티에서 질답을하는 유저의 플로우는

1. 질문자가 질문을 던짐.
2. 답변자가 질문자와 함께 던진 질문에 대해 커뮤니케이션을 하고 결국 해결점을 찾아냄.
3. 질문자는 고마우므로 답변자에게 고마움 표시

입니다.

슬랙같은경우는 이 과정 중 thread내에서 긴 대화를 하기때문에, 제 생각에는 여기에 일일이 포인트를 주지 않아도 될것같습니다. 어짜피 thread안에서 메시지 추가 이벤트는 밖의 채팅방에서랑 같은 이벤트가 발생하고 추가로 이벤트가 하나 더 발생하는 것이기 때문에 추가적인 이벤트는 무시하고 실제메시지에 대한 부분만 처리하면 될것같습니다.

**Comment by Brew-Brew** [comment]
지금 현재 reply에 대한 award부분 수정하려 하는데요! 지금은 message에 대한 스레드가 달릴때마다 점수를 부여하는 방식인것 같은데 올라온 질문에 대한 답변을 유저가 처음 달았을때만 점수를 부여하는식으로 바꾸는걸로 하면 될까요??

**Comment by ho1234c** [comment]
제 의견은 쓰레드와 일반 채팅을 구분할 필요가 없다는것입니다. 내용에서 말씀드린것처럼 메시지가 달리거나 리액션이 발생한 이벤트는 그것이 쓰레드냐 일반 채팅방이냐를 구분하지 않고 발생합니다.
일단 쓰레드에 달리는 추가글이 모두 root 메시지에 대한 답변이라는 보장도 없구요. 따라서 점수를 부여하는방식을 "point to~ 키워드" 혹은 "특정 리액션"만으로 제한하는게 기획측면에서나 구현측면에서나 좋다고 생각합니다.

**Comment by Brew-Brew** [comment]
넵 알겠습니다! 그리고 그 질문에 대한 thread로 달은 답변이 옳은것인지에 대한 판단여부도 명확하지 않을것 같아서 무조건 포인트를 주는것은 좋지않을것도 같네요! 따라서 없애는게 날것 같네요! @swpark6 팀장님도 참고해주시면 좋을것 같아욥!
