### ISSUE TITLE
Success connecting dumbledore-bot on the slack

### ISSUE THREAD

**Issue by wacilpong** [jsdevkr/Dumbledore#16]
![image](https://user-images.githubusercontent.com/27843313/30999081-cd7e96c2-a50d-11e7-9e4a-117b10150581.png)

[학습 -1]
1. 덤블도어 소스코드의 구조를 공부했습니다. 전체적으로 `Dumbledore Constructor`에 프로토타입 함수들로 구성되어 있었습니다. 추후 `ES6 Class`를 사용해 리팩토링하는 것도 좋은 학습이 될 거라고 생각합니다.

2. `sqlite DB`에 대해 학습했습니다. 기본적으로는 `MySql`같은 데이터베이스 시스템이나, 해당 `nodeJs` 프로젝트처럼 가벼운 프로그램에서 사용되기 좋다고 합니다. 결국 SQL문법이니 이를 잘 숙지하고 있으면 될 것 같습니다.

3. 봇 연결 자체를 처음 해보는데, API token을 받아오는 것부터 좋은 공부가 된 것 같습니다. 깨달은 점은 영어를 더욱 공부해서 더 빨리 해결해야겠다는 점입니다.

**Comment by ho1234c** [comment]
저도 봇은 처음 해봐서 공부가 많이 될것같네요. 그리고 멘토님이 백엔드에는 [parse](http://parseplatform.org/)를 달 계획이라고 하시네요

**Comment by gimdongwoo** [comment]
멋집니다! 게다가 1등. 역시 리더님!

그런데 회사원 아니십니까? 어찌 이 시간에 ㅎㅎ

**Comment by wacilpong** [comment]
(원래 몰래몰래 하는 거죠 뭐.. 하핫... !)
