### ISSUE TITLE
발표자료 내용

### ISSUE THREAD

**Issue by wacilpong** [jsdevkr/Dumbledore#162]
디자인을 아예 빼고 들어갈 내용만 적은 파워포인트 자료입니다. 아래와 같은 흐름을 생각하며 만들었습니다. 덤블도어 코드를 발전시킨 내용이 부족해서 중간중간 넣고 싶은데 관련 아이디어도 주세요....  디자인도 잘하시는 분이 도와주세요.

```
1. 왜 하필 덤블도어 교수님? "해리포터 극성팬이어서", "나도 시리같은 걸 만들 수 있는 건가! 생각이 들어서" -> 한마디로 말하면 '재밌을 것 같아서.'

2. 하지만 막상 해보니, github 사용, 협업, 알 수 없는 로직들 등등.. 수많은 난관이 우리 앞에 큰 벽으로 솟아있었음.

3. 매일매일 이 벽에 부딪히며 포기하고 싶을 때도 많았음. 절대로 넘을 수 없을 것만 같았음.

4. 하지만 같은 코드를 매일 보며 비효율적인 부분을 리팩토링해보고, 서로 리뷰해주고, 새로운 기능을 제안해보며 조금씩 벽을 부숴나감.

5. 협업에서의 충돌은 팀을 나누고, Github의 Projects dashboard를 활용해 해결.

6. 모르는 부분은 개인적으로 계속 공부하며 이슈에 남기기도.

7. 120 / 62 / 250 각각 commit, Pull request, issue 개수. 우리가 벽에 준 데미지. 마침내 벽을 부수고 나오는 덤블도어봇
+ 챗봇 사용하는 영상 보여주기
```

[발표ex.pptx](https://github.com/kosslab-kr/Dumbledore/files/1464727/ex.pptx)

**Comment by Brew-Brew** [comment]
제 입장에서 덤블도어 프로젝트를 진행하면서 느낀점이나 어려웠던점 같은것을 정리해서 이슈로 올려 드리겠습니다!
그리고 벽을 깨나가는 느낌도 좋은데욥 ! 저희프로젝트가 진행되는과정을 호그와트 학교가 세워지는? 그런 느낌으로 가도 좋을것 같아요! 이런저런 상황을 거쳐서 하나의 학교가 세워진 느낌으로요! 저희 프로젝트가 덤블도어 교수님 프로젝트이니깐욥! 그렇게 잡으면 피피티 디자인 짜는것도 그런느낌으로 가도 좋을것 같아서욥!! (물론 개인적인 의견입니다 ㅎㅎ)

**Comment by ho1234c** [comment]
pt시작할때 해리포터 bg가 깔린다면..?

**Comment by Brew-Brew** [comment]
commit이나 이슈를 올리는 등의 과정, merge하는 과정들을 학교를 벽돌하나하나 세워나가는 그런느낌으로 가는것이랄까? ㅎㅎ... 건물을 짓는것도 여러사람이 모여 하나의 건물을짓는것이니 학교를 세운것이랑 협업을 통해 하나의 프로젝트를 완성한것이랑 조금은 일맥상통 할수있을것 같아서요 ㅋㅋㅋ

**Comment by Brew-Brew** [comment]
덤블도어 교수님이 있는 하나의 학교 = 덤블도어봇 프로젝트

**Comment by wacilpong** [comment]
해리포터 브금 굿굿 그리고 디자인은 승뀨님 말대로 호그와트학교 이미지로 하고 멘토 교장선생님과 학생들 컨셉으로 하려고 했는데 제 디자인은 매우 비루하고.. 어떻게 깔쌈하면서도 정성들인 것 같이 보일지 모르겠어서... ㅎ...  하하.. 이제 일주일정도 남았으니 계속 업뎃해보게습니다

**Comment by Brew-Brew** [comment]
혹시 도움되는 ppt 템플릿 있으면 찾아보고 올려드리겠습니댜

**Comment by thomasJang** [comment]
도입부에 팀원들이 얼마나 무모하고 열정적인 사람들인가에 대해 
이야기 해주면 좀 더 부드러울 것 같습니다.

챗봇 == AI 라는 환상을 가지고 시작했다는 게 더 좋지 않을까도 생각됩니다.

**Comment by Simhyunjeong16** [comment]
템플릿은 정하셨나요...?너무 늦게 봐서 죄송해요ㅠㅜㅠ
저희가 도울 수 있는게 있다면 말해주세요ㅠㅠㅠ😂😂

**Comment by wacilpong** [comment]
@Simhyunjeong16 템플릿은 정한 거 없어요~! 자료에 들어갈 이미지 or 캡처본 or 영상에 대해 써놨는데 그 자료들을 모아서 이슈로 올려주셔도 좋고, 슬라이드 디자인을 해서 올려주셔도 좋고!! 다 도움이 된답니다ㅎㅎ

**Comment by LeeYeEun2** [comment]
@wacilpong 넵 그럼 자료 찾아보고 올리겠습니다ㅎㅎ
