### ISSUE TITLE
[포인트관련]포인트 주는것에 관련하여 질문

### ISSUE THREAD

**Issue by Brew-Brew** [jsdevkr/Dumbledore#169]
지금 points to @ 코드는 유저가 가진 포인트에서 빠져나가는것이 아니라 그냥 포인트를 주게 짜여져 있는데요!
저명령어로 포인트를 줄때 유저에게서 빠져나가는것이 맞다고 보는데 어떻게 생각하시나요??

멘토님께서 덤블도어봇이 유저들에게 리액션이나 응답을 했을때 포인트를 부여하게 된다고 말씀하신것도 있구요! 이렇게 봇에게 받은 포인트들로 적절한 답변을 하였거나 맘에드는 답변을 하였을때 지식인에서 채택을 하는것과 같이(?) 추가적으로 적절한 답변을 한 유저에게 자신의 포인트에서 포인트를 부여하는것이라고 전 생각했거든요!! 이렇게 되면 예전에 있었던 deductpoint  관련한 내용도 추가되는것이니 이 맥락이 맞을것 같아서요!!

[정리]
1. 덤블도어봇이 질문에대한 답변을 하거나 답변에대한 리액션을 받은 유저들에게 포인트를 주게됨.
2.유저들이 이렇게 받은 포인트들로 적절한 답변을 한 유저에게 포인트를 부여할 수 있게됨. (points to 명령어 )

제의견이구욥 더 추가적으로 변경되거나 수정되야하는 사항 있으시면 말씀해주세요!!!

**Comment by wacilpong** [comment]
자신에게 있는 포인트를 제가 주고싶은 유저에게 주자는 거죠? 좋아용~! 그렇게 만들어야 할 것 같아요! 그럼 만약 포인트가 없는 상태에서 주려고 했을 때 block메시지도 만들어야겠네요 ㅎㅎ

**Comment by ho1234c** [comment]
트랜잭션도 생각을 해봐야겠네요~

+그리고 사실 저도 이것과 관련해서 프론트엔드 대시보드의 메인페이지를 수정했는데요, 원래는 포인트 순위 테이블을 보여주려고 했는데 이 테이블의 순위는 결국 사람이 가장 많은 방을 보여주는 거랑 다를게 없어서... 그냥 빼고 봇 이름을 검색할 수 있는 서치바만 넣어놓은 상태입니다. 검색하면 그 봇이 있는 방의 유저 포인트 랭킹을 보여줄 생각이에요.

**Comment by Brew-Brew** [comment]
넵 알겠습니다. 이부분관련해서는 코드작성하는대로 pr올릴테니 리뷰해주시면 감사하겠습니다!
