### ISSUE TITLE
[질문]봇 api key 질문

### ISSUE THREAD

**Issue by Brew-Brew** [jsdevkr/Dumbledore#17]
봇을 생성하였는데 api key를 어디에 넣어야하는지 모르겠네요 ㅠㅠ

**Comment by ho1234c** [comment]
https://github.com/kosslab-kr/Dumbledore/blob/master/bin/bot.js#L14

env로 넣으시면 될것같아요.

https://github.com/motdotla/dotenv 이런 라이브러리도 있어요

**Comment by Brew-Brew** [comment]
감사합니다! 그런데 node bin/bot.js 라는 명령어로 실행했는데  Cannot find module '../token' 이라는 오류가 뜨네요 ㅠㅠ

**Comment by ho1234c** [comment]
@zx6658 저 코드는 환경변수에서 api 키를 가져오는데 앞의 statement가 false이면 뒤에있는 구문을 실행하는 if 문의 syntax sugar에요. 근데 설정을 안하셨으니 앞에 값은 false고 뒤에 있는게 실행되는데 token.js를 require 하려고 하는데 보니까 파일이 없으니 에러가 나는것같네요

**Comment by Brew-Brew** [comment]
아아 감사합니다!!!!

**Comment by gimdongwoo** [comment]
API키는 환경변수로 넣어줄수도 있고, 코드를 조금 고쳐서 직접 넣을수도 있고.
환경변수에 대해서 한번 찾아보세요.
쉽게 해결해줄 수 있지만, 일부러 환경변수 관련한 쉬운 방법도 제공하지 않고 있습니다. 이렇게 배우는게 좋은거에요.

**Comment by Brew-Brew** [comment]
네네 안그래도 node js에 익숙치 않아서 환경변수 찾아보면서 공부하고있습니다!

**Comment by gimdongwoo** [comment]
환경변수는 사실 nodejs뿐 아니라 java, shell 어떤 언어에서든지 두루 쓰입니다.
JAVA_HOME 도 환경변수 입니다.

**Comment by ho1234c** [comment]
production이랑 develop환경을 나누어서 빌드한다던지 하는 경우에도 쓰입니다.
쉽게는 npm script에서 지정해줄 수 도 있어요. 쉘종류가 다르면 문제가 생기긴하지만요 :)
