### ISSUE TITLE
ppt자료에 관하여!

### ISSUE THREAD

**Issue by songyoungeun** [jsdevkr/Dumbledore#174]
![image](https://user-images.githubusercontent.com/32218545/32783890-9b6e498c-c990-11e7-9777-954bef2f01e1.png)
이런 식의 템플릿도 괜찮은거 같아요!!@-@
![image](https://user-images.githubusercontent.com/32218545/32784142-59be92ca-c991-11e7-8294-f289a0c1930f.png)
![image](https://user-images.githubusercontent.com/32218545/32784153-60792558-c991-11e7-91f8-4f783b281e0e.png)
위에 올린 사진과 같이 해리포터의 비밀지도 컨셉은 어떤가요? 비밀지도가 평범한 종이에 주문을 외우면 사람들의 위치를 발자국으로 표시해줍니다. 이런 컨셉으로 저희가 처음에 주문을 외워 이 오픈소스에 들어와 코드를 보고 아이디어 회의를 하고 코딩을 하고 어려움을 겪고 해결하고 이런 과정들을 지도에 발자국 이미지 활용해서 마지막엔 미션성공!한 마디로 단계적으로 덤블도어앱이 발전해나가는 모습을 표현하는..!?!?이런것도 괜찮을거 같다는 생각을 해보았습니다..!하핫^ㅡ^

**Comment by wacilpong** [comment]
적절히 조합해 슬라이드에 녹여보겠습니다. ㅠ 그리고 이제는 내용에 신경써서 자료를 모아야 할 걱 같아요 !! 자료를 혼자만들려니까 너무 많아서...
