### ISSUE TITLE
[help wanted] 챗봇 사용 비디오클립

### ISSUE THREAD

**Issue by wacilpong** [jsdevkr/Dumbledore#177]
발표 때 라이브로 덤블도어봇을 사용하는 건 약간 무리가 있을 것 같아서 영상자료가 필요합니다. 라이브로는 heroku에 올린 앱 점수판 정도만 보여주려고요. 로컬에서 각 명령어들을 사용하고,  dashboard에 저장되는 정도면 될 것 같습니다. 누가 자료 좀 만들어서 올려주시겠어요?

슬라이드에 자료들을 혼자 만들어야 하는 게 제일 시간이 많이 들어서요 ㅠㅠ
도와주시면 고맙겠습니다..

**Comment by ho1234c** [comment]
아직 프론트파트는 작업중이라 ㅠ 되면 비디오나 gif로 만들게요. 있다고 생각하고 다른부분 먼저 만들어 주심 될듯요!

**Comment by Brew-Brew** [comment]
명령어 입력하는거는 제가 해볼게요!ㅋㅋㅋ
