### ISSUE TITLE
[커밋관련질문] 깃 커밋이 두개의 계정으로 되는것 같아서요 ㅠㅠㅠㅠ

### ISSUE THREAD

**Issue by Brew-Brew** [jsdevkr/Dumbledore#180]
<img width="572" alt="2017-11-16 5 18 27" src="https://user-images.githubusercontent.com/26598542/32880783-39de3c32-caf2-11e7-863c-161addc2373d.png">
저 위와 같이 두계정으로 커밋이 되는것 같은데 왜그런지 알수 있을까요? ㅋㅋㅋㅋㅋ @thomasJang 부멘토님이 만들어주신 영상에도 두개의 계정으로 나와있더라구요 ㅋㅋㅋ

**Comment by Brew-Brew** [comment]
<img width="353" alt="2017-11-16 5 24 07" src="https://user-images.githubusercontent.com/26598542/32881006-04889838-caf3-11e7-90a4-483c9c6f811b.png">

**Comment by ho1234c** [comment]
로컬에서 사용하는 툴에 계정이 여러개가 등록되어있는게 아닐까요

**Comment by Brew-Brew** [comment]
살펴보니 sourcetree로 커밋한것들 zx6658@likelion.org 계정으로 되어있고 merge되었을때는 zx6658@naver.com계정으로 되어있네요 ㅎ...

**Comment by zx6658** [comment]
author를 바꿔바야겠어요 ㅎㅎ...

**Comment by Brew-Brew** [comment]
author를 바꿔보려했는데, This is nothing to take lightly: you will create new commit objects in this process, which can become a serious problem for your collaborators - because they might have already based new work on some of the original commits. 이문장때문에 무서워서 바꾸질 못하겠어욥

**Comment by ho1234c** [comment]
그냥 계정하나를 지우면 안되나요?

**Comment by Brew-Brew** [comment]
그러면 지운 계정으로 했었던 커밋들은 오류같은게 나는것은 아닌가용?

**Comment by ho1234c** [comment]
툴에서 설정이 어떻게 되어있는지를 모르겠네요. 근데 아마 config에서 user설정해주는것같아요. 어짜피 이미 push한건 다 갈아엎지 않을거면 어쩔 수 없고, 앞으로 안나게해야하는건데 로컬에서 지우는게 원격에 영향을 미칠것 같진않네요.

**Comment by Brew-Brew** [comment]
네네 그래서 이미 푸시된건 그냥 놔두려구요 ㅋㅋㅋㅋ 계정 설정은 변경해놨습니다!ㅎㅎ... 깃잘쓰는 길은 멀고도 험한거 같아요... 계정 두개로 분할되서 커밋이 나눠져서 아쉽긴하지만...ㅎㅎ앞으로 더커밋하면 되니깐용
