### ISSUE TITLE
[질문]reaction point 관련

### ISSUE THREAD

**Issue by Brew-Brew** [jsdevkr/Dumbledore#188]
[질문]
 
현재 100점 이모지를 달았을때만 point를 주고있는데 으뜸표시(thums up), 웃는표시 (grinning),하트 <3
이모지를 달았을때도 점수를 주려하는데 어떠한 이모지들을 줄때 점수를 주는게 좋을까요..?

+추가질문
general 채널에있는 덤블도어봇은 merge되고있는 코드가 자동으로 적용되는것인가요..????

**Comment by wacilpong** [comment]
좋아요 ㅎ 자주쓰는 이모지가 그정도니까.. 그리고 CI서버에서 master에 머지된 브랜치를 통째로 heroku에 반영하는 거라서 자동으로 적용되고 있는 거 맞습니닷!

**Comment by Brew-Brew** [comment]
아아 넵 감사합니다! 그런데 그 슬랙에서 명령어 입력하여 수행하는 영상은 gif형식으로만들어도 되려나요..? 발표에 필요한 자료욥!

**Comment by wacilpong** [comment]
넹 상관없을 것 같아요ㅋㅎ
