### ISSUE TITLE
질문있어요 -!

### ISSUE THREAD

**Issue by saejungHyun** [jsdevkr/Dumbledore#19]
![default](https://user-images.githubusercontent.com/20151534/31015182-c2b77ed8-a559-11e7-981a-1b75ef22be7d.JPG)
이렇게 뜨면요..
특정 워크스페이스를 탈퇴(비활성화)해야하나요?

**Comment by gimdongwoo** [comment]
추가할 수 있는 봇의 갯수가 제한이 있어서 그렇구요.

그래서 아까 한번 정리했는데요. 지금 또 하나 정리했으니 다시 해보세요~

**Comment by saejungHyun** [comment]
아하 그렇군요 그런데 되는 듯 하였는데 다시 똑같이 뜨네용 ㅠ

**Comment by gimdongwoo** [comment]
https://dumbledorebot.slack.com/admin

이미 만들어진게 아닐까요? 다시 7개가 되었거든요.

추가로 integration들을 정리했습니다.
