### ISSUE TITLE
질문있습니다,,

### ISSUE THREAD

**Issue by songyoungeun** [jsdevkr/Dumbledore#20]
<아미몬-심현정 이예은 송영은> 

![image](https://user-images.githubusercontent.com/32218545/31015407-e1726f3a-a55a-11e7-9e2f-46f4010e1bf6.png)
저희가 위에 npm install까지 실행해보았습니다. 그리고 ##Running dumbledore에서 오류가 발생했습니다,,,,
이렇게 실행시키는게 맞는 방법인가요?

**Comment by gimdongwoo** [comment]
명령이 환경변수 설정과, node 실행 2가지가 합쳐져 있는 상태인데요.
윈도우 기본 커맨드라인에서는 `변수명=값` 형식의 환경변수 설정 명령이 동작하지 않습니다.
윈도우용 bash셀을 사용하거나, 실행되는 bin/bot.js를 수정해서 실행시킬 수 있습니다.
일단 쉬운 방법은 bin/bot.js를 수정해서 실행하는 것이죠.
`환경변수` 관련해서 검색해보세요.

**Comment by ho1234c** [comment]
win10 이라면 배쉬랑 명령어는 다르긴하지만 파워쉘에서 명령어가 있어요.
아니면 npm으로 pm2 설치하시고 샘플파일 참고하셔서 pm2.json 만드셔서 pm2로 실행하시면 환경변수 설정된 환경에서 실행하실 수 있어요
