### ISSUE TITLE
(일단은) 발표자료 최종 업데이트

### ISSUE THREAD

**Issue by wacilpong** [jsdevkr/Dumbledore#204]
일단은 최종 업데이트 슬라이드입니다. 내일 (`11/19. 일요일 12:00 ~`)  @thomasJang 멘토님과 함께 더 얘기 나누고 빌딩할 예정입니다. 혹시 시간 되시는 분들도 부담갖지 말고 선릉 오셔서 같이 얘기해요~! ㅎㅎ

[final_ex.pptx](https://github.com/kosslab-kr/Dumbledore/files/1484556/final_ex.pptx)

**Comment by Brew-Brew** [comment]
최고에요!!!! 꼭가보고싶은데 GDG devfest 신청을 해놔서 흑흑..ㅠ아 그리고 heroku restart 한번 해주시겟어용? student 클래스에 잘못된 데이터가 들어가있어서용..ㅠㅠㅠㅠ..
