### ISSUE TITLE
Pull Request 관련 질문

### ISSUE THREAD

**Issue by wacilpong** [jsdevkr/Dumbledore#21]
같은 소스코드를 각자가 수정, 개발하고 있는데
알아서 마음대로 수정하고 커밋 후 Pull request를 보내도 되나요..? ㅜㅜ

일단 각자의 repository에만 커밋해놓을까요...?

**Comment by ho1234c** [comment]
제 생각에도 지금 거의 로직만 가져오고 나머지는 통으로 바꾸다시피 해야할것같아서... 손대는걸 미루고있어요. 아직 참여하지 못하신 세분도 있는거같구요. 오늘내로 각자 scope를 정하는게 좋을거같아요.

**Comment by gimdongwoo** [comment]
본래 오픈소스 컨트리뷰션은 선빵치는 사람이 짱입니다.
마음껏 PR보내세요.

PR 보냈는데 merge conflict가 뜬다면 컨트리뷰터가 메인 리파지터리와 자신의 리파지터리를 다시 동기화 하여, conflict를 해결하고 다시 PR을 보내야하는 것입니다.

**Comment by gimdongwoo** [comment]
초심자들을 위해서 git의 브랜치와 PR전략에 대해서 강의할 예정입니다.

**Comment by ho1234c** [comment]
제가 너무 플젝하듯이 접근했나보네요. ㅋㅋ 마음대로 PR보내는걸로!

**Comment by gimdongwoo** [comment]
네. 그리고 오픈소스는 왕창 뜯어고친 PR은 오너가 더럽고 깐깐하게 안받아줍니다ㅋㅋㅋㅋㅋ
