### ISSUE TITLE
[질문]node bin/bot.js database error

### ISSUE THREAD

**Issue by Brew-Brew** [jsdevkr/Dumbledore#22]
![image](https://user-images.githubusercontent.com/26598542/31041587-c726d1ca-a5d2-11e7-81e9-072fb994c6c3.png)

![image](https://user-images.githubusercontent.com/26598542/31041610-28da0d7e-a5d3-11e7-8618-8fc2007dca58.png)

node bin/bot.js로 실행했을때 DATABASE ERROR: {Error: SQLITE_CORRUPT: database disk image is malformed at Error (native) errno:11,code:'SQLITE_CORRUPT'} 와 같은 에러가 나오는데 어떻게 해결해야 할까요 ㅠㅠ

**Comment by ho1234c** [comment]
데이터베이스가 깨진거같네요. 일단 안에 백업할건 없으니까 db파일 날리고 다시 실행해보세요.
dbpath는 db의 경로를 바꾸지 않으실거면 지정하지 않으셔도 됩니다.  그리고 그... 경로안에 한글은 웬만하면 지양하시는게 좋아요.
