### ISSUE TITLE
[질문] 봇 관련 질문 -cannot read property of

### ISSUE THREAD

**Issue by Brew-Brew** [jsdevkr/Dumbledore#24]
-dumbledore.js
![image](https://user-images.githubusercontent.com/26598542/31042815-3d663ee4-a5eb-11e7-934b-636032c37172.png)

-bot.js
![image](https://user-images.githubusercontent.com/26598542/31042820-5aa83f20-a5eb-11e7-86ef-026eb2435355.png)

-error화면
![image](https://user-images.githubusercontent.com/26598542/31042816-4980dcb6-a5eb-11e7-9c95-4a674f8244a6.png)

bot.js 를 실행했을때 웰컴메시지를 채널에 띄워보려고 저런식으로 해보았는데 에러가나네요 ㅠㅠ 채널설정 관련하여 밑의 issue를 읽고 channel[3]이라는 값을 주었습니다. 0으로 바꿔봐도 똑같은 문구의 에러가 나네요 ㅠ!

**Comment by swpark6** [comment]
3은 제 채널입니다, console.log(this.channels) 를 해보셔서 자신의 채널이 어디있는지 확인해보세요.

**Comment by Brew-Brew** [comment]
console 로 로그를 찍어봤는데 채널이 undefined라고 나오네요ㅠ

**Comment by ho1234c** [comment]
channels라는 객체에 뭐가 들어가있는지 확인해봐야 할것 같아요

**Comment by swpark6** [comment]
그 이전코드가 정상 작동 하는지 확인해볼 필요가 있을것 같아요, 다른명령어는 잘 되나요??

**Comment by Brew-Brew** [comment]
node bin/bot.js 명령어를 cmd창에 입력하면 아무에러도 뜨지않으니 run은 되는것 같은데 ㅠ

**Comment by swpark6** [comment]
this.postMessageToChannel('sewon-sandbox', 'Welcome to Hogwarts everyone!' ...(생략)
이런식으로 그냥 채널 이름을 입력해도 괜찮습니다..
channels 가 undefined인건 해결을 해야 할 문제인것 같구요..
