### ISSUE TITLE
질문있습니다!!

### ISSUE THREAD

**Issue by Simhyunjeong16** [jsdevkr/Dumbledore#26]
![q1](https://user-images.githubusercontent.com/32221552/31044699-17127004-a60f-11e7-9afa-b7096d9dc35d.PNG)
![q2](https://user-images.githubusercontent.com/32221552/31044701-1988af10-a60f-11e7-9263-35f89d958e93.PNG)
![q](https://user-images.githubusercontent.com/32221552/31044709-4220c782-a60f-11e7-905d-eaa77a1cf55f.PNG)
이렇게 바꿨는데..돌아가지않습니다ㅜㅠ

**Comment by swpark6** [comment]
dbPath가 잘못되었네요.. dbPath는 특별한 경우 말고는 설정을 하지 않아도 path.resolve(process.cwd(), 'data', 'dumbledore.db') 여기에서 잘 잡아줍니다.

**Comment by Simhyunjeong16** [comment]
![default](https://user-images.githubusercontent.com/32221552/31044837-33bcc904-a612-11e7-9e1e-e314bb824c53.PNG)
![default](https://user-images.githubusercontent.com/32221552/31044839-36a47932-a612-11e7-842d-3152cc4dbb2b.PNG)

설정하지 않았는데 밑에 아무것도 뜨지않습니다:(....

**Comment by swpark6** [comment]
실행중인겁니다. 실행 중 로그 메세지라던지의 출력문이 없기 때문에, 확인해보고싶은 부분이있다면 console.log 로 아무거나 찍어보세요~ 예를들어 
![image](https://user-images.githubusercontent.com/14174350/31044862-c3261212-a612-11e7-8fad-06dc71283396.png)
이런 부분에 console.log 를 추가해보세요..

**Comment by Simhyunjeong16** [comment]
감사합니다!

**Comment by gimdongwoo** [comment]
데몬(백그라운드 동작)이기 때문에 console.log로 뭔가 찍지 않으면 아무것도 안뜨는게 정상입니다.
