### ISSUE TITLE
channel 질문이요ㅜㅜ

### ISSUE THREAD

**Issue by LeeYeEun2** [jsdevkr/Dumbledore#27]
<img width="688" alt="default" src="https://user-images.githubusercontent.com/31236688/31044744-02678418-a610-11e7-9431-bdeac263374d.PNG">

<img width="467" alt="2" src="https://user-images.githubusercontent.com/31236688/31044760-3eae5b7c-a610-11e7-8367-ab4da0d9cfdc.PNG">

2번째 사진처럼 channel을 바꿔줬는데 channel[0]이 undefined라고 씁니다.ㅜㅜ 뭐가 잘못된 걸까요?ㅜㅜ

**Comment by ho1234c** [comment]
깃헙채널과 슬랙채널은 다른기능이에요

**Comment by gimdongwoo** [comment]
저건 github integration이 이루어지는 슬랙 채널을 설정해서 github 이벤트에 따른 봇의 동작을 만들려는 기능입니다.
