### ISSUE TITLE
[질문] 슬랙 채널에 bot을 추가해야하는지 여부

### ISSUE THREAD

**Issue by Brew-Brew** [jsdevkr/Dumbledore#28]
제가 슬랙에 익숙치가 않아서요 ㅠㅠ bot.js를 실행하면 자동으로, 설정된 채널에 봇이 추가되는 건가요?? 아니면 add an app(?) 으로 채널에 봇을 따로 추가를 한 상태에서 bot.js를 실행하는건가요? ㅠ

**Comment by swpark6** [comment]
![image](https://user-images.githubusercontent.com/14174350/31045029-f9ba7e1e-a615-11e7-835d-246ecc24a2c3.png)
![image](https://user-images.githubusercontent.com/14174350/31045033-0495d6f8-a616-11e7-9fa6-e8804e52fd2f.png)
적당한 봇을 채널에 초대 해야 합니다.

**Comment by Brew-Brew** [comment]
헉 그러네요 ㅎㅎ.. 이제 다 제대로 되네욥! 감사합니다!
