### ISSUE TITLE
리액션 점수 보상

### ISSUE THREAD

**Issue by swpark6** [jsdevkr/Dumbledore#31]
슬랙 답변에 대해 특정 리액션을 하면 그 유저에게 점수부여를 하는 기능을 추가하면 괜찮을것 같습니다.
리액션 갯수에 따라 소팅 하는것도 괜찮을거같구요.

![image](https://user-images.githubusercontent.com/14174350/31045405-e9645bd6-a61d-11e7-96cc-a86aba49be7d.png)

대충 뼈대만 잡아봤는데 다른분들 의견이 궁금합니다.

**Comment by wacilpong** [comment]
리액션이면 이모지같은 것을 말씀하시는 건가요? 리액션 후 덤블도어 교수님이 바로 점수를 주는 아이디어 괜찮은 것 같아요!!

**Comment by gimdongwoo** [comment]
슬랙의 리액션 기능을 사용하는 아이디어 좋네요!

**Comment by ho1234c** [comment]
슬랙의 리액션도 이벤트에 잡히는지 확인해봐야할것같네요

**Comment by swpark6** [comment]
이벤트에 잘 잡힙니다. 위 코드는 의도대로 작동하는것을 확인했습니다. message.type 로 'reaction_added' 와  'reaction_removed' 로 캐치가 가능합니다. 또한 message.reaction 으로 어떤 리액션을 받았는지, 제거했는지 알 수 있습니다. 위 코드의 '+1' 은 엄지손가락을 올린 리액션입니다.

**Comment by Brew-Brew** [comment]
좋은 아이디어 같아요!!!

**Comment by swpark6** [comment]
#109
