### ISSUE TITLE
Git 학습

### ISSUE THREAD

**Issue by HyeonUkCho** [jsdevkr/Dumbledore#32]
![image](https://user-images.githubusercontent.com/18049575/31045520-7a2ec550-a620-11e7-9ed4-55352ae4a63c.png)

notice에 올려주신 링크와 tyr-git을 학습한 후 github에 올려보았습니다.
추석 연휴 동안 dumbledore에 대해 파고 들어보겠습니다!!

**Comment by gimdongwoo** [comment]
Good!
