### ISSUE TITLE
구동 성공했습니다 그런데,

### ISSUE THREAD

**Issue by saejungHyun** [jsdevkr/Dumbledore#33]
![success](https://user-images.githubusercontent.com/20151534/31045604-840cec62-a622-11e7-9e1d-f095f4c343b1.JPG)
bot1으로 하면 성공하는데요.

제가 만든 봇 saejbot으로 하면 토큰 값과 봇 이름만 다를뿐인데
![err1](https://user-images.githubusercontent.com/20151534/31045609-993ff8b8-a622-11e7-802e-8dccbd007bfc.JPG)
이러한 에러가 나서요 ㅠㅠ 왜 그런 것인지 궁금합니다

**Comment by thomasJang** [comment]
.name을 쓰려는 코드가 있는데 undefined여서 그런데요. 대게는 해당라인에 console.log 해보시는 것이 쉽게 추적 가능합니다.
