### ISSUE TITLE
nodeJs cron 학습

### ISSUE THREAD

**Issue by wacilpong** [jsdevkr/Dumbledore#36]
[학습 -2]
1. nodeJs에서 스케줄러를 구현하기 위해 `cron `라이브러리를 학습했습니다. CronJob이라는 객체를 `new`로 만들어, `start()` 메소드로 구동하는 것이 주 원리입니다. 

![cron](https://user-images.githubusercontent.com/27843313/31052914-edf56a88-a6cb-11e7-9743-ab6943efa84a.PNG)

2. `ES6 class`를 사용할 때 상속받는 상위클래스가 있다면, `constructor`에서 `super()`를 호출한 후 `this`를 사용할 수 있다는 것을 알았습니다. 아래 코드에서 super()없이 this 이하를 실행하려고 하면 `this is not defined `에러를 뱉어냅니다.

![class](https://user-images.githubusercontent.com/27843313/31052915-f141e842-a6cb-11e7-836d-665a0ebc07f7.PNG)

**Comment by gimdongwoo** [comment]
Good!
