### ISSUE TITLE
17. 10. 01 발견한것들

### ISSUE THREAD

**Issue by ho1234c** [jsdevkr/Dumbledore#40]
### 모듈화
- replyWithDumbledore 메소드가 코드 줄수의 절반이상을 차지합니다. 이 함수를 잘 쪼개는게 중요해보입니다.

### bot 상속
- Slack API 라이브러리를 상속받으면서 SlackBot의 api를 this를 통해서 사용할 수 있습니다. 따라서 특별한 경우가 아니면 bot객체를 전달할 필요가 없습니다. (하지만 콜백으로 쓰이는 함수와 this를 바인딩하는 부분에서 주의가 필요) 또한 this객체에 직접 접근하는 경우가 많은데 [SlackBots.js](https://github.com/mishk0/slack-bot-api) 에 보면 웬만한 getter는 다 있습니다.  (비동기라 promise를 반환합니다)

### raw query
- 쌩쿼리가 비지니스로직에 포함되어있습니다. 개선이 필요해보입니다.

### const value
- 챗봇이다보니 코드속에 문자열이 비교적 많은데, 따로 빼면 좋을것 같습니다.

**Comment by gimdongwoo** [comment]
맞습니다. 기능별로 객체지향 원칙에 따라 분리를 해야하죠.

하나씩 컨트리뷰션 해보도록 하지요!
