### ISSUE TITLE
중간에 있는 commit은 괜찮은건가요?

### ISSUE THREAD

**Issue by swpark6** [jsdevkr/Dumbledore#41]
![image](https://user-images.githubusercontent.com/14174350/31055481-69da5ad2-a6fe-11e7-9883-84b1d316a4c2.png)

SVN만 쓰다보니까... merge에 대한 이해가 많이 부족합니다.
이런식으로 중간에 껴있있는 커밋은 나중에 제 Pull requests 가 허락되었을 때 어떻게 되는건가요?
질문 하기 전에 제가 이상하게 작업하고있는것은 아닌지 궁금합니다.

**Comment by ho1234c** [comment]
저는 svn을 안써봤지만... commit을 누가 했는지는 git의 입장에선 별로 중요하지 않다고 생각하시면 될것 같아요. git에 입장에서 중요한건 코드입니다. 지금까지의 commit을 누가 작성했건간에 레포의 코드랑 충돌이 나지 않는다면 정상적으로 pr이 날아갑니다.

**Comment by gimdongwoo** [comment]
git hash tree 입니다. 중간에 끼어 있는것처럼 보이는 것이지 실제로 sourcetree에서 보면 바라보고 있는 선행노드는 더 위쪽에 링크되어 있을것이라 문제는 없습니다.

다만 master 브랜치에 커밋을 한것은 나중에 PR이 거부되었다거나 하는 상황에서 다른 history를 가지게 되기 때문에 master 브랜치에 커밋을 권하지 않는 것입니다.
