### ISSUE TITLE
10/2 학습

### ISSUE THREAD

**Issue by LeeYeEun2** [jsdevkr/Dumbledore#43]
<아미몬>
저희는 오늘 node.js와 javascript에 대해서 공부하였습니다. 또한 멘토님의 영상을 보고 따라해 보면서 git과  github에 대한 개념과 용어들을 조금 더 이해할 수 있었습니다. 내일은 node.js공부와 코드 공부를 병행하겠습니다.

**Comment by gimdongwoo** [comment]
굿!
