### ISSUE TITLE
질문있습니다...

### ISSUE THREAD

**Issue by Simhyunjeong16** [jsdevkr/Dumbledore#45]
멘토님이 올려주신 동영상을 보며 따라하고있었는데..merge가 되지않습니다ㅠㅜ
![qqqq](https://user-images.githubusercontent.com/32221552/31056932-3cfc2b46-a715-11e7-81a2-100e6443da00.PNG)
![qq](https://user-images.githubusercontent.com/32221552/31056933-3da77686-a715-11e7-8938-b5a94feed1f0.PNG)

**Comment by ho1234c** [comment]
pull 할때 히스토리가 달라서 머지가 안되는것같네요.

https://stackoverflow.com/questions/37937984/git-refusing-to-merge-unrelated-histories

**Comment by gimdongwoo** [comment]
history가 전혀 일치하지 않는데요. Fork 한 리파지터리가 아닌 모양입니다.

git clone이 아니라 download 하였다거나 한거 아닌가요?
