### ISSUE TITLE
첫 과제 관련 질문드립니다!

### ISSUE THREAD

**Issue by Hyo9** [jsdevkr/Dumbledore#46]
안녕하세요 한 발 늦게 첫 과제를 시작하게 된 김효진이라고 합니다.

여러 먼저 참여해주시고 열심히 이끌어주시는 분들의 질문을 보고 아래와 같은 과정까지는 실행해볼 수 있었습니다. 

- 슬랙 channel 형성(#hyo9ch)
- 슬랙 봇 형성(hyo9bot)
- 덤블도어 fork 후, git clone하여 로컬에서 실행
- npm install하기
-bot.js에서 token, name, githubChannel 설정
-dumbledore.js에서 name설정

-후에 bash에 토큰키 node bin/bot.js 실행 
-console.log를 통해 bot.js가 잘 실행되는 것을 확인

그러나!!! console.log(this.channels);가 계속 undefined네요.
전체 코드에서 계속 검색해봤지만, githubChannel과 slack채널을 어디서 연결해주는지 파악하기가 어려워 이렇게 도움을 청합니다.

여러가지 접근을 해봤다고 생각했는데, 막상 바꾼 코드는 얼마 없네요..

많은 분들이 첫 과제를 끝내시고 새로운 일에 돌입할 시기에 이런 기초적인 질문 드려 죄송합니다ㅠ 아직
 많이 미숙하지만열심히 따라가도록 하겠습니다!

<dumbledore.js>
![dum](https://user-images.githubusercontent.com/26561441/31064673-aa21ce92-a779-11e7-983b-e45422981b50.jpg)
<bot.js>
![bbot](https://user-images.githubusercontent.com/26561441/31064674-aa2247e6-a779-11e7-873c-030efb9bd05e.jpg)
<개발환경 c9// c9 중 node.js 템플릿 이용-여기에 깃클론>
![c9ide](https://user-images.githubusercontent.com/26561441/31064672-aa1e954c-a779-11e7-9c2e-77b0d15b4224.jpg)

<봇이 add 된 사진>
![add bot](https://user-images.githubusercontent.com/26561441/31064675-aa26410c-a779-11e7-847c-cf728d84e496.jpg)

**Comment by HyeonwookCho** [comment]
this.githubChannel로 찍어야하지 않을까요

**Comment by HyeonwookCho** [comment]
아 channels가 있네요,,

**Comment by ho1234c** [comment]
잉? 과제같은게 있었나요? 왜 저는 몰랐지...  

저도 github channel관련한 기능은 테스트를 못해봤지만 optional한 부분이기 때문에 다른 기능에는 문제가 없을겁니다. 저기서 this.channels가 undefined인 이유는 저 컨텍스트에서의 this는 global이기 때문이에요. channels라는 프로퍼티가 존재하는 this는 Dumbledore 클래스 안에서 호출했을 때의 this입니다. 자바스크립트는 렉시컬 스코프를 따르기때문에 this가 호출되는 곳에 따라 의미가 다릅니다. Dumbledore 클래스 안에서 호출해보시면 정상적으로 출력될거에요. Dumbledore객체는 Slack Bot 을 상속받기 때문에 prototype chaining에 의해 Bot객체에 접근이 가능하기 때문인데요. this를 통한 직접접근보다 [slack-bot](https://github.com/mishk0/slack-bot-api)에 보시면 getChannels라는 메소드를 자체적으로 제공하는데 이를 통한 접근을 권장합니다.

**Comment by gimdongwoo** [comment]
@ho1234c 첫번째 과제는 slack의 notice 채널에 등록된 내용입니다. 읽고 분명히 댓글도 다셨거든요ㅋㅋ
```
...
# 처음으로
- Dumbledore의 코드와 구조를 살펴보고, README문서에 따라 슬랙에 봇을 적용해봅니다.
- 모두 관리자 권한을 드렸으니, 각자의 채널과 봇을 만들어 덤블도어가 동작하게 만들고, 성공한 것을 이슈에 등록하세요.
...
```

**Comment by gimdongwoo** [comment]
네. 슬랙 채널부분은 코드상의 버그입니다. 슬랙봇으로 부터 채널 목록을 수신하는 부분이 잘못되어 있어요.
누군가 고쳐주실것이라고 생각하고 있어요.
github 채널 부분은 우리 slack에서 github봇이 동작하는 채널이 있는것처럼 특정채널에 올라온 github 봇의 이벤트에 따라 추가적인 동작을 개발하기 위한 요소인데, 역시 미구현되어 있습니다.
