### ISSUE TITLE
머지질문있습니다

### ISSUE THREAD

**Issue by saejungHyun** [jsdevkr/Dumbledore#48]
![gfdgdgd](https://user-images.githubusercontent.com/20151534/31066704-d495b692-a789-11e7-9c6b-d07daa9d7e25.JPG)

어제올려주신대로 머지했는데 잘 된것이 맞는지 궁금합니다..
멘토님이 올려주신 것 처럼 master들이 한 선상에 있지 않아서 궁금해서요 ㅠ

글 수정했습니다

**Comment by ho1234c** [comment]
의도한것이 무엇이지 몰라서 잘된건지는 모르겠지만 한 선상에 없는건 브랜치를 나누셔서그래요! 히스토리를 좀 더 깨끗히 하려면 rebase를 찾아보시면 도움이될거같습니다. 
히스토리 관리하는건 되게 어려운거같아요 ㅠ

**Comment by gimdongwoo** [comment]
local의 master가 origin으로 push 되지 않았는데, test 브랜치는 origin으로 push되지 않은 상황이구요.

그리고 강의에서 말한것 처럼 master 브랜치에 커밋을 해놔서 향후에 PR을 보낼때 문제가 생길 가능성이 높습니다.

**Comment by saejungHyun** [comment]
master브랜치에 커밋을 해놓은 상황을 어떻게 되돌릴 수 있을까요? ㅠㅠ 소스트리에서 변경전을 클릭하고 현재 브랜치를 이 커밋으로 초기화 하여 hard로 모든것을 지우고자 했는데 한 후에도 바뀌지 않네요 ㅠㅠ..

**Comment by ho1234c** [comment]
소스트리는 잘기억이 안나지만... ```git reset --hard HEAD~갯수``` 로 되지않나요?
