### ISSUE TITLE
10.2학습내용 [pull request & fork한것 동기화& git 학습 ]

### ISSUE THREAD

**Issue by Brew-Brew** [jsdevkr/Dumbledore#51]
**- 원래 repository 에서 Fork 해온것을 merge되어 변경사항이 있는 것을 동기화 해보는 작업을 올려주신 강의를 보며 해보았습니다.**

[정리]
-> fetch를 해야만 remote repository 로 부터 data(?)를 가져옴. master가 변경, 만약 처음 클론해온 상태이면 fetch를 해야 local 에 master 브랜치가 생김
->여기서 branch란 커밋사이를 가볍게 이동할 수 있는 pointer 같은것.
->깃은 기본적으로 master 브랜치를 만듬
-> HEAD란 특수 포인터로써, 지금 작업하고 있는 로컬 브랜치(?)를 가리킴
->깃 저장소 만드는 방법
  1. 이미존재하는 프로젝트 디렉토리에 GIT 저장소 생성 git init => local branch생성
  2. 이미존재하는 repository로부터 복사 (강의에서 사용한 방법)
  git clone remote는 origin이 되고 master 라는 branch 가 로컬에 생성됨.
  origin 은 source tree같은 tool에서 이름변경가능

**pull request 작업을 해보았습니다.**
[정리]
특정이슈나 bug? =>branch를 생성하여 작업
원래코드와 상관없는 독립적인 개발? => branch를 생성하여 작업

**강의를 학습하며 어려웠던점**
여러개의 remote나 local의 branch들을 생성하거나, pull하거나 push 하는 여러 과정들이 아직까지는 많이 헷갈리고 어려웠던 것 같습니다.  강의를 복습하며 더 학습해야 할 것 같습니다. 아직 까지 git에 대해서는 많은 학습이 필요한 것은 사실인것 같습니다.

**강의를 들으며 깨달은점 및 정리 (틀린 부분이 있으면 지적해주세요!)**
git에 대해서는 초심자였으므로, 강의를 통해, 브랜치라는 것의 개념을 알게 되었고, 혼자 현재 코드와 상관없이 어떤부분에 대해서 개발을 할때에는 local에 임의의 branch를 생성하여 여러 변경사항들의 개발이 완료되면 커밋을 하게되고 이를 내 remote repository에 push하게 되고 이를 pull request로 보내어 main repository에 merge를 요청할 수 있다는 것을 알게 되었습니다. 

 ->만약 merge가 받아들여진다면 main remote 리포지토리를 fetch를 통해 master branch를 변경 시키고, local master branch, 자신의 remote repository역시 master를 변경시켜 같은 선상에 위치하게 작업한다. 그런다음 원래 작업했던 branch를 삭제해 준다.

**Comment by gimdongwoo** [comment]
맞습니다. 브랜치는 굳이 지울 필요는 없지만, 보통은 정리 차원이서 지웁니다.
