### ISSUE TITLE
[10/2] Repository 동기화

### ISSUE THREAD

**Issue by HyeonUkCho** [jsdevkr/Dumbledore#53]
Repository 동기화 동영상 강의를 본 후, 소스트리를 사용하지 않아 cmd에서 해보았습니다...

// remote kosslab-kr/dumbledore 추가
git remote add kosslab https://github.com/kosslab-kr/Dumbledore.git

// kosslab-kr/dumbledore 변경 사항 확인
git kosslab fetch

// 변경 사항을 local의 branch로 가져오기
git checkout -b kosslab_master kosslab/master

// 기존의 Local에 master와 kosslab_master Merge하기
git merge master kosslab_master

이 부분에서,,,,branch를 만들지 않고 master를 변경하며 개발하여 conflict가 발생했습니다.

동영상에서 branch를 만들어가며 개발을 하여야 한다는 점을 알고
처음으로 돌아가 다시 fork하고 clone을 하여 이번에는 branch를 만들어 테스트하고 있습니다.

// merge한 master를 fork한 repository에 push
git push origin

이 명령어는 다시 동기화가 되어 있어서 'Everything up-to-date'라고 떴습니다...

conflict를 해결하고 다시 fork를 하지 않았다는 점이 아쉬웠습니다.

**Comment by gimdongwoo** [comment]
굿!
