### ISSUE TITLE
테스트 프레임워크 및 CI

### ISSUE THREAD

**Issue by wacilpong** [jsdevkr/Dumbledore#54]
조만간 CI를 구축할 계획이신 것 같아서, Travis와 관련된 문서를 읽고 학습했습니다. 그리고 이와 더불어 js 테스트 프레임워크 mocha, jasmine, karma에 대해서도 학습했습니다.

[학습 -3]
1. http://www.tisa-software.com/news/blog/217-jasmine-mocha-javascript-testing-framework-comparison
2. https://docs.travis-ci.com/user/getting-started/
Travis는 깃허브에서 레파지토리를 CI로 hosted한 후, `.travis.yml` 파일에 `language : {사용한 언어}`를 설정해주어 연결합니다. 테스트뿐만 아니라 DB를 세팅하거나 빌드환경을 사용자가 다시 설정할 수도 있다는 것을 알았습니다.

**Comment by gimdongwoo** [comment]
좋아요. 일단은 Test 가 우선으로 해야 할 일입니다.
