### ISSUE TITLE
학습^u^

### ISSUE THREAD

**Issue by songyoungeun** [jsdevkr/Dumbledore#55]
<20171002 아미몬>
node.js가 서버환경에서 어떤 방식으로 네트워크 입출력을 처리하는지 공부하였습니다. node.js가 이벤트를 기반으로 비동기방식으로 처리하기 때문에 제가 지금 배우고 있는 서버 방식과는 다름을 인지하게 되었습니다. node.js의 전역 객체부터 살펴보며 공부를 하며 dumbledore.js 코드는 처음부터 살펴보며 공부할 계획입니다.

● node.js는 모듈을 사용해 기능을 확장한다
● 모듈은 기능을 쉽게 사용하고자 메서드와 속성 을 미리 정의해 모아 놓은 것이다
● 생성한 모듈을 다른 자바스크립트 파일에서 추출할 때는 require()함수를 사용한다
● cron모듈: 일정시간마다 반복되는 작업을 자동화 시킬 수 있음
             '* * * * * *'('초 분 시간 년 월 일'), *은 매 단위 마다 실행
         ex)매주 월요일 11시 라면
           ('00  00  11 * * 1')
● path모듈 : 파일 다룰 때 파일 패스에서 파일 이름과 폴더 이름 구별 or확장자 ,확장자                  제외 파일 이름 등을 알아낼 때 사용
● fs모듈: 외부의 파일을 읽거나 쓰려면 require("fs")를 통해 nodejs의 file system모듈을

**Comment by gimdongwoo** [comment]
좋습니다! 한걸음씩!!
