### ISSUE TITLE
봇 이름에 대한 포인트 부여 오류

### ISSUE THREAD

**Issue by swpark6** [jsdevkr/Dumbledore#56]
![image](https://user-images.githubusercontent.com/14174350/31123679-d87afaf4-a87b-11e7-877e-d71a699b1f65.png)

![image](https://user-images.githubusercontent.com/14174350/31123683-e03b5b44-a87b-11e7-936b-6b32f0b38aca.png)

![image](https://user-images.githubusercontent.com/14174350/31123693-e890584e-a87b-11e7-9aad-0432818ab45a.png)

계속해서 점수가 2점만 부여가 되서 원인을 찾아보았더니  [홍진호의 저주인줄]
포인트부분을 파싱하는 부분에서 봇 이름에있는 숫자를 point로 인식하는 문제가 있습니다.
즐거운 추석 보내세요...

**Comment by wacilpong** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ콩..의.. 저주... 세원님도 즐거운 추석 보내세요!

**Comment by ho1234c** [comment]
그러고보니 저도 봇이름이 ho1234c라서 무조건 100포인트를 주는 이슈가 있었는데 깜박했네요.ㅋㅋ 그런데 points to 와 points from은 앞에 봇이름없이도 호출가능한 키워드더라구요. 그렇게 호출하길 의도한거
같은데... 여튼 키워드기준으로 파싱하도록 수정하겠네요!

**Comment by gimdongwoo** [comment]
파싱을 저런식으로 일차적으로 하는것 자체가 문제이죠ㅎㅎㅎ

해결해봅시다.
