### ISSUE TITLE
코드 질문있습니다!

### ISSUE THREAD

**Issue by HyeonUkCho** [jsdevkr/Dumbledore#58]
![image](https://user-images.githubusercontent.com/18049575/31130548-aa91b472-a892-11e7-9ced-15c98b65b6a1.png)

[질문 사항] (dumbledore.js)
1. self가 Dumbledore 클래스를 받는것이 맞나요?
2. this.users.filter에서 filter가 어디서 나온건가요?

**Comment by swpark6** [comment]
![image](https://user-images.githubusercontent.com/14174350/31131232-7eb27a24-a894-11e7-9389-4a89e4677118.png)

![image](https://user-images.githubusercontent.com/14174350/31131339-d3417766-a894-11e7-9966-490e9d4a5cdc.png)


2. filter는 이쪽의 filter가 아닐까까요?

**Comment by HyeonUkCho** [comment]
감사합니다!

**Comment by ho1234c** [comment]
자바스크립트의 클래스문법은 사실 프로토타입으로 구현한 syntax sugar에요. 저 메소드안에서 this는 생각하시는 대로 Dumbledore가 맞습니다. (정확히는 Dumbledore 클래스를 통해 생성한 인스턴스겠네요)
그리고 fillter는 세원님이 말씀해주신것처럼 es6부터 제공되는 자바스크립트의 high order function중 하나에요. https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

**Comment by HyeonUkCho** [comment]
감사합니다!

**Comment by HyeonUkCho** [comment]
한가지 더 질문 드립니다...
![image](https://user-images.githubusercontent.com/18049575/31132196-2f393c64-a897-11e7-9b34-78eb8b542941.png)

----------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/18049575/31132238-44913a62-a897-11e7-97ef-8df1d5f6fc3e.png)

---------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/18049575/31132276-5a2662d0-a897-11e7-821b-96a73544aefd.png)

---------------------------------------------------------------------------------------------------------------

이런 에러가  뜨는데 channels을 못가져오는거 같은데,,,맞나요?
왜 이러는 걸까요...?

**Comment by ho1234c** [comment]
우선 channels가 Array 타입이 맞는지부터 확인해보셔야 해요. 제 생각에는 undefined가 찍히지싶네요. fillter는 Array의 프로토타입 속에 지정되있기때문에 Array만이(정확히는 Array라는 프로토타입을 가지는 객체) 사용할 수 있습니다.

**Comment by gimdongwoo** [comment]
channels를 가져오는 구문이 없으니 상속받은 slackbot이 넣어줘야 하는데 그 동작 관련해서 코드를 잘못 작성했을 수도 있고, slackbot 쪽 코드가 바뀌었을 수도 있죠.

**Comment by HyeonUkCho** [comment]
@gimdongwoo 감사합니다!
