### ISSUE TITLE
뒤늦은 구동 성공ㅠㅠ!

### ISSUE THREAD

**Issue by Hyo9** [jsdevkr/Dumbledore#59]
와 정말 백년 묵은 체증이 내려가는 것 같네요 ... 흑흑...
제대로 셋업하고 구동을 아무리 해봐도 bot이 대답을 하지 않아서 정말 당황스러워서,
결국 onMessage에 채널 list를 띄워봤는데(js에 익숙하지 않아 this.가 어디에 먹는지도 한참 찾았답니다..)
제가 만든 채널만 없더라구요?! 알고보니 private하게 생성된 채널은 봇을 연결하지 못하는 것으로 결론이 났습니다. public 최고.... 신기한 것은 channels 어레이가 [0]부터 쌓이는게 아니라, 새로운 채널을 만들면 알파벳순으로 인덱스가 뒤바뀌는듯 했습니다. 

+이 외에도 오늘 멘토님들의 강의자료를 보고 git commit, push, merge에 대해 공부하였습니다. sourcetree를 사용하니 커멘트창보다 훨씬 편하더라구요 신세계!
++제가 경험해본 웹 개발 프레임워크는 루비온레일즈인데, 서버 구동 방식이 루비온레일즈와 많이 다름을 깨달았습니다.
+++npm에 대해 알아보았습니다. 루비온레일즈에서 gem과 약간은 비슷한 역할이라는 것을 깨달았습니다.

이번 연휴를 계기로 node.js에 대해 더 파헤쳐보도록 하겠습니다! 
![kakaotalk_20171004_031837080](https://user-images.githubusercontent.com/26561441/31141600-d0bbeb84-a8b2-11e7-88a2-d5146646dcb2.jpg)

**Comment by gimdongwoo** [comment]
프로그래밍은 생각, 검색, 시도, 소거의 싸이클이죠.

수고 많았습니다!

**Comment by Brew-Brew** [comment]
루비온 레일즈라묜 ㅎㅎ멋사 하셨나용! 반갑습니다 헤헤

**Comment by Hyo9** [comment]
와 반갑습니다!! :)  너무 못따라가고있는 것 같아 멋사라 하기에도 민망하네요 ㅠㅠ 화이팅..!! 반갑습니다!!

**Comment by HyeonUkCho** [comment]
헐 저도에요 반갑습니다ㅎㅎㅎ

**Comment by Hyo9** [comment]
와 반가워요!! :)
