### ISSUE TITLE
오류 질문합니다ㅜㅡㅜ

### ISSUE THREAD

**Issue by songyoungeun** [jsdevkr/Dumbledore#61]
<아미몬>

![default](https://user-images.githubusercontent.com/32218545/31185861-0ae7b198-a968-11e7-826d-a3243c3cfe80.PNG)

코드를 분석하다가 구동을 시켜보려 했는데 이런 오류가 납니다...!!모듈에 무슨 문제인걸까요...?ㅜㅡㅜ

**Comment by wacilpong** [comment]
혹시 pull 받고 처음 돌리시는 건가요? 그럼 npm install 쳐주세요!! Dependencies들을 최신버전으로 업데이트했거든요ㅎㅎ

**Comment by gimdongwoo** [comment]
git pull 하면서 코드가 어디가 바뀌었는지 보시면 좋습니다.
