### ISSUE TITLE
[아이디어] 챗봇 팀변경관련

### ISSUE THREAD

**Issue by Brew-Brew** [jsdevkr/Dumbledore#62]
<bot-name> can i please join <team-name> 명령어로 초기에는 팀에 들어가지는데, 
다른 팀으로 혹시 변경이 되는지 하여 위 명령어를 다시 입력해, 다른 팀명으로 바꿔 해보았는데, 팀 변경이 되지 않네요!ㅠ

부가적인 요소일것 같기는 하나, 저 명령어로도 팀변경이 가능하게 쿼리문을 바꾸(?)거나, 
팀변경 명령어를 만들어야 하지 않을까 하는 제 개인적인 의견입니다.! 여러 게임이나 스포츠만 보더라도 팀변경은 자주 일어나는 일이니깐요 ㅎㅎ

기존 명령어들로 위 과정을 실행 하려면
<bot-name> obliviate @<user-name> 으로 db에서 삭제하고,
<bot-name> can i please join <team-name> 명령어로 다시 팀을 가입해야 하더라구요!

**개인적인 의견이였습니다!!ㅎㅎ**

**Comment by LeeYeEun2** [comment]
좋은 아이디어인 것 같습니다ㅎㅎ

**Comment by gimdongwoo** [comment]
팀에 대한 것은 논의가 필요하긴 하나, 실제로 팀 개념은 없애고 개인에게 적립되는것이 나을것 같아서 보류중입니다.
