### ISSUE TITLE
[Discussion] DB instance modularization

### ISSUE THREAD

**Issue by ho1234c** [jsdevkr/Dumbledore#63]
현재 코드에선 db 인스턴스가 클래스 내부 인스턴스로 저장되고 있어서 생성자 클래스의 this를 통해서 db에 접근해야 합니다.  모든 메소드를 한 class에 넣기는 힘들기 때문에 코드가 모듈화되면 모듈안에서 db에 접근하기 위해서 call이나 bind 같은 문법으로 수동으로 this를 바인딩해야 합니다. 

db와 관련된 기능들을 따로 모듈화한다면 필요에 따라 불러와서 사용할 수 있기때문에 함수호출이 편해지고 비교적 스코프를 많이 생각하지 않아도 된다는 장점이 있습니다. 하지만 지금과 같이 인스턴스를 생성할 때마다 db 인스턴스의 스코프가 생기진 않기때문에 여러개의 dumbledore 인스턴스를 생성하는 경우가 발생한다면 이를 관리하는 기능을 따로 구현해야합니다.

db 모듈화에 대해서 어떻게 생각하시나요?

**Comment by gimdongwoo** [comment]
DB 작업이 들어가는 부분은 parse js sdk로 변경할 생각입니다.
http://docs.parseplatform.org/js/guide/
sql에 대한 코스트 없이 간단하게 js object 관점에서 사용할 수 있는 훌륭한 라이브러리 입니다.
이 부분에 대한 코드는 차주에 제가 적용하도록 하겠습니다.
로컬에서 개발하기도, 테스트하기도, 배포하기도 적합한 형태라 전 많은 곳에서 parse를 사용하고 있습니다.

**Comment by Brew-Brew** [comment]
노드js는 라이브러리가 정말 다양하네용!

**Comment by ho1234c** [comment]
parse는 한번도 안써봤는데 ORM도 제공을 하는군요. 좋아보입니다.

**Comment by Brew-Brew** [comment]
Orm이라면 아이바티스 같이 자동으로 맵핑 해주는 건가요?? 정말 좋은것 같아욥

**Comment by gimdongwoo** [comment]
ORM이라기 보단 parse는 분류상 backend as a service입니다.
server-side code, trigger라던가 hook, dashboard 등을 지원하죠.
지원하는 DB는 mongodb과 postgresql 이 있구요.
