### ISSUE TITLE
10/6 dumbledore.js 학습

### ISSUE THREAD

**Issue by HyeonUkCho** [jsdevkr/Dumbledore#64]
bot1 say hello to students을 넘어 코드 분석을 통해

10 points to Gryffindor
bot1 who is winning the house cup
bot1 can i please join Gryffindor? 등등의 문장을 입력해보며 전체적인 흐름을 공부해보았습니다.

남은 추석 연휴동안 더욱 열심히 공부해보겠습니다

**Comment by gimdongwoo** [comment]
수고하셨습니다!
