### ISSUE TITLE
[10월 7일 학습] 아미몬

### ISSUE THREAD

**Issue by LeeYeEun2** [jsdevkr/Dumbledore#65]
<img width="314" alt="3" src="https://user-images.githubusercontent.com/31236688/31306225-83bafee8-ab86-11e7-88f7-b6d7116e82e3.PNG">
저희가 코드를 공부하던 중에 사용자를 랜덤하게 팀 가입을 시키기 위해 bot1에게 명령어를 넣어 줬는데 사진과 같이 3개의 대답이 나오면서 3개의 팀에 가입됩니다. 그래서 코드를 분석해봤는데 분석이 어려워 질문 드립니다.ㅜㅜ 왜 3개가 나오는지 궁금합니다.

**Comment by ho1234c** [comment]
replyWithDumbledore, addStudentToHouse, rollTheDice 메소드의 코드를 보여주세요

**Comment by Simhyunjeong16** [comment]
따로 고친 코드는 없습니다ㅠㅜ
![1](https://user-images.githubusercontent.com/32221552/31307783-d469cc74-aba5-11e7-9b7b-ad6b04a28f17.PNG)
![2](https://user-images.githubusercontent.com/32221552/31307786-dd1baaae-aba5-11e7-972b-7aafb4db050f.PNG)
![3](https://user-images.githubusercontent.com/32221552/31307788-e2a41628-aba5-11e7-88f2-10bf05854858.PNG)
![4](https://user-images.githubusercontent.com/32221552/31307791-e813e0b6-aba5-11e7-8b74-8acd40d116fe.PNG)

**Comment by ho1234c** [comment]
코드는 보통 이미지말고 텍스트로 주시는게좋아요. 근데 저대로라면 한번만 실행되는게 맞는걸로보이는데요...  디버깅을 해봐야 알수있겠네요. 최종적으로 Lucy0229님은 어떤 하우스에 가입되있는걸로 나오는지, 디비삭제하고 다시 해도 같은 결과가 나오는지 테스트해보시면 좋을거같아요.

**Comment by LeeYeEun2** [comment]
다시 실행해보니 한번만 나오네요~ 감사합니다~~
