### ISSUE TITLE
[질문]코드 관련 메소드앞 언더바

### ISSUE THREAD

**Issue by Brew-Brew** [jsdevkr/Dumbledore#66]
코드를 분석하고 있는데, 코드를 보면 run을 제외한 다른 메소드 앞에는 거의 다 언더바 ( _ )가 붙어있는데 혹시 그이유를 알 수 있을 까요???  특정 기능을 위해서인지, 아니면 그냥 관례적으로 쓰이는 건지 궁금해서요!

**Comment by Brew-Brew** [comment]
+추가질문

어떤 메소드는 message를 인자로 받거나 쓰는데 어떤 메소드는 originalMessage 를 인자로 쓰는데 두 값이 어떤 차이가 나는지 가늠이 안가서요 ㅠㅠ

**Comment by ho1234c** [comment]
일종의 컨벤션입니다. private한 함수를 명시적으로 이름에 표기하는거에요. run을 제외한 메소드들은 내부의 로직을 위해 사용된다는 뜻인거죠. 그런데 자바스크립트에서는 이름에 표기한다고 private하지않습니다.  용도가 그렇다는거지 문법적으로는 외부에서도 호출할 수 있습니다. 하지만 1차적으로 사용자가 이 함수는 내부에서 사용되기 위해 작성됐으니 외부에서 호출하면 안되겠구나라는걸 알리기위해 언더바를 붙여줍니다.

**Comment by ho1234c** [comment]
+결국 할당되는건 같은 객체인데요. 그냥 string 파싱 시점을 기준으로 Message와 originalMessage라는 이름으로 나뉘는것같네요.

**Comment by Brew-Brew** [comment]
그렇군요!! 감사합니다 알려주신 정보로 더 살펴봐야겟네욥!
