### ISSUE TITLE
[아이디어] 포인트 부여나 특정 리액션시 그 질문과 그에대한 답안 저장

### ISSUE THREAD

**Issue by Brew-Brew** [jsdevkr/Dumbledore#67]
메신저의 특성 상 데이터가 흘러가 버리기 때문에 소중한 참여와 공헌이 축적되지 않는점을 해결하기 위해 이프로젝트가 진행되는걸로 알고있습니다! 포인트나 이모지로 그 공헌을 인정해주는것 말고도 그렇게 인정할 수 있었던 답변이나 질문들은 모두 소중한 정보이고 데이터이기 때문에, 모아 놓는것도 나쁘지 않겠단 생각도 방금 들어서요!!ㅎㅎ

따라서 어떤 답변에 대한 적절한 답을 했을때 포인트를 주게되거나 앞서말했던 이모지?같은 것으로 특정 리액션을 하게될텐데요! 그런 액션이 일어난 질문과 그에대한 답변들은 그럴때마다, DB에 질문과 그에대한 답변을 추가하여 각 사용자(student)가 어떤 답변으로 점수를 얻었거나 이모지를 얻었는지 확인할수 있게 명령어로 따로 구현하여 보여주는것도 어떨까 하는 생각이듭니다!!

**Comment by gimdongwoo** [comment]
https://github.com/kosslab-kr/Dumbledore/issues/31
좋은 의견이구요.
이미 이곳에서 논의되고 있는 아이디어 입니다 :)
