### ISSUE TITLE
npm install 오류 질문 드립니다

### ISSUE THREAD

**Issue by LeeYeEun2** [jsdevkr/Dumbledore#68]
<img width="679" alt="no repository" src="https://user-images.githubusercontent.com/31236688/31316389-216c28e8-ac67-11e7-9c25-bc6c80e661b0.PNG">

npm을 업데이트 시키기 위해 npm install을 했는데 npm install을 하면 dumbledore의 repository가 없다고 뜹니다. 계속 검색하고 수정해봤는데 해결이 되지 않아 질문 드립니다.ㅜㅜ

**Comment by wacilpong** [comment]
제대로 검색은 안해봤지만 아마 package.json 파일이 잘못되어서 그런 것 같아요. 혹시 모르니 package.json파일싱크 확인해주세요! 빠진내용이 없는지요.

**Comment by ho1234c** [comment]
No repository field라는 메시지는 나와있는것처럼 warning이에요. 말그대로 package.json에 repository라는 필드가 지정되지 않아서 알려주는거고 스크립트 실행에는 문제가 없습니다. 보고싶지않으면 silent 옵션인가 quiet옵션인가를 주시면 됐던걸로 기억해요. 저기서 잘 보셔야하는 부분은 
```bash 
Failed at the sqlite3@3.1.13 install script.
```
인데요. sqlite3 설치하면서 에러가 발생하는거에요. 찾아보니 gcc랑 node-gyp관련된 문제인거 같은데 node_modules폴더 날리고 다시 설치해보셨나요?

https://github.com/mapbox/node-sqlite3/issues/612 여기 참고해보세요

**Comment by gimdongwoo** [comment]
https://github.com/mapbox/node-sqlite3/issues/637
visual studio가 설치되어 있는데 설정이 잘못 잡힌경우,
`run npm config set msvs_version 2015`
또는 `run npm config set msvs_version 2012` 등으로 셋팅을 해줘야하는 모양이군요.

그리고 윈도우에서 개발상의 경로상는 한글이 없는 환경을 권장합니다.
윈도우 환경의 한글은 유니코드가 아니기 때문에 여러가지 문제를 일으킵니다.

사실 java던 node던 개발을 윈도우에서 하는것 자체를 권하진 않습니다... 윈도우는 visual studio 쓸때나 필요하죠.

**Comment by FireflyStars** [comment]
fetchMetadata: sill resolveWithNewModule webpack-dev-server@3.1.10 checking installable status
this state does not change
