### ISSUE TITLE
실행환경의 통일과 lint가 필요합니다.

### ISSUE THREAD

**Issue by ho1234c** [jsdevkr/Dumbledore#70]
1. 모든 분들이 실행은 성공한걸로 알고있습니다. 아마 각자 환경변수등의 문제로 실행하는 방법이 다르실것 같은데 이를 통일할수있는 스크립트를 작성하면 좋을것같네요. readme의 업데이트도 필요합니다.(영어 능력자분 ㅠ)

2. 멘토님께서도 말씀하신것 처럼 lint 룰이 필요합니다. airbnb를 베이스로 하는게 어떨까 싶네요.

화요일 회의참여를 못해서 이슈남깁니다.

**Comment by gimdongwoo** [comment]
좋은 의견입니다. esLint는 사용하고 있는게 이미 있어서 적용만 하면 되는데, Lint는 제가 리드하도록 하지요.

**Comment by gimdongwoo** [comment]
esLint를 포함해서 코드를 커밋했습ㄴ디ㅏ.
