### ISSUE TITLE
[질문] 테스트코드에서 환경변수는 어떻게 해야할까요?

### ISSUE THREAD

**Issue by ho1234c** [jsdevkr/Dumbledore#76]
PR이 ci에서 막혀서 봤더니 필요한 값들을 환경변수에서 가져오기 때문에 travis ci와 같은 툴에서 실행 테스트를 할수가 없습니다. 어떻게 해야할까요?

**Comment by gimdongwoo** [comment]
travis ci에 테스트에 필요한 최소한의 환경변수는 셋업되어 있습니다.

**Comment by gimdongwoo** [comment]
PR에 셋업된 환경변수가 적용되지 않는거 같군요. 확인해보겠습니다~

**Comment by gimdongwoo** [comment]
암호화된 키로 환경변수를 추가했습니다. https://docs.travis-ci.com/user/encryption-keys/

https://github.com/kosslab-kr/Dumbledore/commit/872f9e5a5602247a3bd11893420abaaaf445b621
