### ISSUE TITLE
[깃헙관련 질문]새로 커밋 된 내용으로 로컬 리포지토리 업데이트중 

### ISSUE THREAD

**Issue by Brew-Brew** [jsdevkr/Dumbledore#77]
예전에 올려주신 깃헙강의를 다시 보며 로컬 리포지토리를 koss_lab remote리포지토리에 새롭게 커밋된 내용(eslint 등등..)을 동기화 시키고 있는데, 저번에 강의를 보면서도 궁금했었는데요!
 
강의에서는 kosslab 리모트 리포지토리의 master 브랜치를 새롭게 체크아웃한 브랜치인 kosslab_master는 로컬 master 브랜치에 바로 merge해주는데, 이와 달리 자신의 깃헙 remote 리포지토리에는 로컬에서 push를 하게 되는데요! 

1. 오픈소스 리모트 리포지토리 master 브랜치를 로컬과 merge. 
2. merge한 로컬 master브랜치를 fork해온 내 리모트에 push.

꼭 이런 과정으로 거쳐서 해야하나요??

그리고 여러명령어를 입력해보면서,제 로컬에 있는 dumbledore.db 파일이 변경되어 이 변경사항이 commit되어 있는것 같은데,이 db파일이 kosslab 리포지토리와 달리 제 fork한 리포지토리에는 commit이 두번 더 되어있는데 큰 상관은 없는건가요?? merge는 잘 되었습니다!
data라는 내용의 커밋은 db가 변경되어 commit을 제가 한것입니다..!

![image](https://user-images.githubusercontent.com/26598542/31387471-84dc1e8e-ae05-11e7-9334-80a0cdca95b9.png)

**Comment by ho1234c** [comment]
첫번째는 이해가 잘 안되네요 ㅠ
다만 저같은 경우는
1. 원본 레포와 본인계정의 원격 레포로 remote 를 두개만들고
2. 필요한 걸 작업한뒤 
3. 본인 레포에 push하기 전에 아까 원본 레포에서 fetch를 받고
4. 현재 자신이 작업해놓은것과 merge
5. 그리고 본인 레포에 push를 하고 pr을 날립니다.

두번째는 우선 .gitignore 파일을 건드리지 않으셨다면 db파일을 깃이 트래킹하지 않을텐데요... 아마 본인 계정의 레포에 변경사항을 push하신것같네요. 그 변경사항이 정상적으로 commit하신거라면 pr을 날리시면됩니다.

**Comment by gimdongwoo** [comment]
db파일은 지워버리고 초기버전을 sample.db로 남겨 놓은 상태입니다.
정상적인 상황이라면 db파일이 커밋에 포함될 일이 없습니다.

master branch를 update하는 방법은 여러가지가 있으나, git은 기본적으로 로컬이 우선이고,
작업이 완료된 후 remote로 push하는 것이니 작업이 나누어져 있습니다. 편하실대로 하세요~
