### ISSUE TITLE
[nodemon 관련질문] npm run dev시 오류

### ISSUE THREAD

**Issue by Brew-Brew** [jsdevkr/Dumbledore#78]
![image](https://user-images.githubusercontent.com/26598542/31421265-6948de06-ae81-11e7-892f-076ca9e96517.png)
위와 같이 환경변수를 넣어서 npm run dev로 실행시 위와같이 오류가 뜨는데 이유를 알수있을까요?

**Comment by gimdongwoo** [comment]
이건 NodeJS 버전 문제입니다. NodeJS에서 async를 쓰려면 7.0이상이어야 하거든요.
그래서 package.json에도 명시되어 있습니다.

https://github.com/kosslab-kr/Dumbledore/blob/3be2a112d4be72221224337ff6756f753f455537/package.json#L30

**Comment by ho1234c** [comment]
저는 nvm쓰는데 편하더라구요

**Comment by gimdongwoo** [comment]
@ho1234c 저는 n 사용합니다ㅎㅎ
윈도우에서 nvm밖에 없죠.
https://johnpapa.net/multiple-versions-of-node-with-n/

**Comment by ho1234c** [comment]
맥에는 저런것도 있군요! 역시 맥을써야...  nvm보다 사용성이 뛰어난것 같아 보이네요. 저것도 심볼릭링크를 사용하는 방식이겠죠?
