### ISSUE TITLE
global installing of jasmine is needed 

### ISSUE THREAD

**Issue by wacilpong** [jsdevkr/Dumbledore#79]
![jasmine](https://user-images.githubusercontent.com/27843313/31422550-7cea39b6-ae89-11e7-897c-8a0c145d22d9.JPG)

`devDependencies`로 jasmine이 명시되어 있었으므로, 당연히 내부 node_modules로 생성이 됩니다. 그래서 프로젝트 루트에서 `jasmine` 명령어가 가능할 줄 알았는데 아니네요. 혹시나 해서 `npm i -g jasmine` 를 실행하고 루트에서 다시 해보니 됩니다.

생각해보면 당연히 제 로컬에 설치를 해야 명령어를 사용할 수 있는 건데 말이죠 ㅎㅎ 도움은 안될 것 같지만, 혹시나 같은 문제가 발생할까봐 이슈로 남겨둡니다. 참고하세요!

**Comment by ho1234c** [comment]
설치하셨다고해도 직접 cli를 통해 사용하려면 npm script를 통해야합니다. npm run test를 입력해보시면 정상적으로 jasmine을 실행할겁니다. 혹은 최근에 나온 npx를 사용해보세요.

**Comment by gimdongwoo** [comment]
네. global로 설치 안해도 npm 통하면 실행됩니다.
아니면 `./node_modules/jasmine/bin/jasmine` 으로 경로 지정하면 실행됩니다.

`npm test`로 하면 알아서 해줍니다ㅎㅎ
