### ISSUE TITLE
[질문] npm test 명령어

### ISSUE THREAD

**Issue by wacilpong** [jsdevkr/Dumbledore#81]
```
λ npm test

> dumbledore@1.1.0 pretest D:\RoomyNode\Dumbledore
> npm run lint

> dumbledore@1.1.0 lint D:\RoomyNode\Dumbledore
> eslint -c .eslintrc lib
```

궁금한게 있는데... package.json에서는 분명 test 스크립트에 jasmine을 실행하게 되어 있는데요. 제가 커맨드에 `npm test `혹은 `npm run test`를 치면 위와 같이 esLint가 실행되더 라고요. 혹시 제가 뭔가 착각하고 있는게 있을까요? 아니면 `pretest`라는 스크립트 명령어는 직접 치지 않아도 자동으로 실행되서 그런 건가요? ㅠㅠ

**Comment by gimdongwoo** [comment]
pretest에 eslint가 있어서 그렇습니다.

https://github.com/kosslab-kr/Dumbledore/blob/3be2a112d4be72221224337ff6756f753f455537/package.json#L7

**Comment by ho1234c** [comment]
일종의 훅이에요! post도 있습니다.
http://www.marcusoft.net/2015/08/pre-and-post-hooks-for-npm-scripting.html
