### ISSUE TITLE
[Proposal, Questions] slackbots library separation

### ISSUE THREAD

**Issue by ho1234c** [jsdevkr/Dumbledore#82]
Dumbledore 클래스는 slackbots을 상속받습니다. 그리고 내부 코드를 보면 slackbots과 강력한 의존관계가 있는데요. 사실 slackbots의 역할은 그저 메시지를 전파해주는것 밖에없습니다. 

따라서 이 부분을 따로 분리하면 좋을것 같습니다. 현재는 이걸 위해서 클래스 초기화때 만들어논 객체를 계속 끌고다닙니다. 그래서 메소드 호출에 있어서 인스턴스변수를 이용해야하는 문제로 혼란스러운점이 있습니다. 예를들어

https://github.com/kosslab-kr/Dumbledore/blob/3be2a112d4be72221224337ff6756f753f455537/lib/controller/replyWithDumbledore.js#L22

https://github.com/kosslab-kr/Dumbledore/blob/3be2a112d4be72221224337ff6756f753f455537/lib/controller/replyWithDumbledore.js#L205

이런부분들에서 this를 파라미터로 계속 전달해줘야 하거나 call을 통해 메소드를 호출해야 합니다. db 접근을 위한 객체도 마찬가지지만 db가 바뀔예정이기 때문에 이는 나중으로 미뤄도 될것같습니다.

또한 slackbots을 분리하면 slackbots에 대한 의존성이 줄기때문에 만약 다른 플랫폼으로 확장하는 경우에도 쉽게 가능하다는 장점이 있을것이구요.

<del>그래서 저는 bot모듈을 만들어서 처음 초기화시에 객체를 만들어놓고 필요한 부분에서만 호출하는 식으로 구현해 보고있었는데, 많은 블로그등을 찾아서 따라해봐도 싱글톤 모듈 구현이 생각보다 어렵더라구요. 클로저를 쓰더라도 resolve되는 경로가 다르면 만들어 놓은 객체를 사용하지 않는 문제가 있었습니다.</del>

slackbots을 분리하는것에 대해 어떻게 생각하시는지, 어떻게 분리할수 있을지 의견이 있으신가요?

-----

+테스트환경이 잘못되었더군요. 경로가 달라도 기본적으로 같은 모듈을 불러옵니다. 따라서 클로저를 이용하면 문제없이 같은 객체를 불러올 수 있습니다. 그리고 노드에서는 모듈을 캐싱하더라구요. 테스트해보니 여러 모듈에서 불러오더라도 require할때마다 새롭게 객체를 생성하는게아니라 있던 객체를 사용합니다. 따라서 지금상황에선 싱글톤패턴을 사용할 필요가 없겠네요.

**Comment by wacilpong** [comment]
분리 동의합니다! 멘토님께서 페이스북용도 만드신다고 하셨던 것 같아서 확장성 문제도 그렇고 분리하는 게 좋을 것 같아용‥ 지금의 제 짧은 생각으로는 slackbot자체를 최소한의 세팅으로 일단 구동해놓고, 구동된 봇을 모듈화해서 전역으로 쓰면 될 것 같은데 생각해보니 이게 싱글톤 패턴인ㄷ‥‥ 혹시 만들어놓은 객체를 사용하지 않는다는게 계속 봇을 새로 구동시킨다는 의미인가용?

그리고 말씀하신대로 db가 곧 바뀔테니 이후에 처리해야할 것 같아요! Db connection부분이 덤블도어 클래스에서 또 중점적인 부분이고 구조가 바뀔 것 같으니까요. 그나저나 종호님 진짜 하드캐리하십니다ㅜㅜ‥

**Comment by HyeonUkCho** [comment]
별다른 side effect가 없다면....좋은 아이디어 같습니다. 분리 동의합니다. 싱글톤으로 한다면 좋을 것 같습니다. 근데 자바스크립트로는 싱글톤을 해본적이 없어서,,,방법은 고민해봐야 할 것 같습니다.

**Comment by ho1234c** [comment]
@wacilpong 제가 제일 한가해서 그래보이는것같아요...  회사다니면서 하시기가 더 힘드시죠 ㅋㅋ;

근데 롤한판하고와서 두분 글 읽어보고 다시 생각해보니까 setting정보를 굳이 Dumbledore에서 받아올 필요가 없군요! 다시해봐야겠어요. 몇시간동안 삽질했는데 역시 잘안될때는 환기가 필요한가봐요 ㅎㅎ

**Comment by ho1234c** [comment]
https://github.com/kosslab-kr/Dumbledore/pull/84

**Comment by gimdongwoo** [comment]
건전한 컨트리뷰션이 이루어지고 있군요. 좋습니다!
