### ISSUE TITLE
10/12 nodemon 설정

### ISSUE THREAD

**Issue by HyeonUkCho** [jsdevkr/Dumbledore#83]
윈도우에서 nodemon 설정 시 시행착오를 남겨봅니다. 혹시 같은 문제 겪으시고 있다면 참고하시기 바랍니다..

1. cmd에 node install -g nodemon 입력. -> nodemon을 전역으로 install
2. README에는 cp  ./node_sample.json  ./nodemon.json 이라 되어 있지만 cp가 먹질 않아서
    copy  ./node_sample.json  ./nodemon.json 입력.
    하지만 복사할 수 없는 파일이라고 뜹니다.
    그래서 직접 nodemon.json 파일을 만들고 ./node_sample.json의 내용을 복붙했습니다.
3. nodemon.json에 api_key 추가
4. 마지막으로 READMA에 npm run dev을 치면 nodemon 명령어가 없다고 뜹니다.
    환경변수에 npm을 추가해야만 합니다.
     npm config get prefix 명령어로 npm의 위치를 찾아 추가해줘야 합니다.

![image](https://user-images.githubusercontent.com/18049575/31500841-8485918c-afa3-11e7-9972-f0894e7f9a9b.png)

이후 npm run dev를 입력하면 정상적으로 작동합니다.

**Comment by ho1234c** [comment]
일반적인경우라면 저기 등록되어있는 C:\Program Files\nodejs\ 이 안에 npm이 있습니다. 그래서 nodejs를 설치하기만해도 npm이란 명령어도 글로벌 cli로 사용할 수가 있어요. 뭔가 지우시거나 패스에 문제가 있으셨나보네요.

**Comment by HyeonUkCho** [comment]
그런거 같아요ㅜㅜ

**Comment by gimdongwoo** [comment]
윈도우 개발환경은 참 힘들어요...
