### ISSUE TITLE
[버그] 콜백 실행

### ISSUE THREAD

**Issue by swpark6** [jsdevkr/Dumbledore#87]
![image](https://user-images.githubusercontent.com/14174350/31538454-90b65d72-b040-11e7-8438-13be728de6f0.png)

[Congratulations Gryffindor! Gryffindor house has 92 points!]
계속 이전 명령어의 콜백이 따라나오는 이유가 뭘까요?

점수는 올라가지 않네요.

**Comment by ho1234c** [comment]
이거 아직 문제 있으신가요? 제가 실행해봤을땐 정상적으로 나와서요. 어떤환경이신가요?

![image](https://user-images.githubusercontent.com/11595293/31813709-581b0f26-b5c2-11e7-819f-fd39654149a6.png)

**Comment by swpark6** [comment]
해결된 것 같습니다~!
