### ISSUE TITLE
code convention

### ISSUE THREAD

**Issue by wacilpong** [jsdevkr/Dumbledore#9]
기존 덤블도어 js에서 카멜표기법(ex. onStart, newProject... ETC)으로 코드가 쓰여 있습니다.
그러므로 이후에도 const선언과 class를 제외한 문자들은 camel case로 통일하는 것이 어떨까요!
너무 당연한 이슈였다면 죄송합니다.....

by. 한아름(Roomy)

**Comment by gimdongwoo** [comment]
당연히 카멜케이스가 표준입니다.
곧 eslint도 적용해보죠.

**Comment by gimdongwoo** [comment]
eslint를 적용하였습니다.
