### ISSUE TITLE
mongodb-runner error in windows

### ISSUE THREAD

**Issue by ho1234c** [jsdevkr/Dumbledore#91]
이번에 도입한 parse라는 서비스에 mongodb-runner라는 모듈이 의존성이 있는것같은데요. 윈도우에서 실행하실 때 아래와 비슷한 에러 발생하시면 사용중인 터미널에 관리자권한 주시면됩니다.

![image](https://user-images.githubusercontent.com/11595293/31584698-17a3fe6c-b1ee-11e7-912d-d7638d75faf9.png)

**Comment by gimdongwoo** [comment]
굳 팁입니다! 역시 윈도에서 노드개발은 여러가지로 힘들군요...

**Comment by wacilpong** [comment]
저도 윈도우라 에러나길래 바로 관리자권한주고 해결했습니다 고마워요~~
