### ISSUE TITLE
[bug, question] slackBot 호출문제

### ISSUE THREAD

**Issue by wacilpong** [jsdevkr/Dumbledore#94]
`replyWithDumbledore.js`에서 slackBot 클래스에 대한 선언이 없기 때문에 `~ is not function node`에러가 발생합니다. 

현재는 아래와 같이 `bot.js`에서 server를 생성할 때 dumbledore 클래스를 생성하면서 함께 slackBot이 만들어지고 있습니다. 따라서 여기서 호출된 slackBot을 사용하도록 바꿔야할 것 같습니다.

```
server.create().then(() => {
  ...
  // dumbledore bot
  const dumbledore = new Dumbledore({
    token,
    dbPath: process.env.BOT_DB_PATH,
    name: process.env.BOT_NAME,
    githubChannel: process.env.BOT_GITHUB_CHANNEL_ID
  });
  ...
}, console.error);
```

그리고 이에 따라 질문이 있습니다. server가 만들어질 때 선언되는 객체를 parse server에 저장하고 사용할 방법이 있을까요? 서버가 생성될 때 선언하므로  `exports`로 모듈화하여 사용할 수가 없을 것 같아서요.. 혹은 제가 놓치고 있는 것이 있다면 알려주시면 고맙겠습니다 !

**Comment by wacilpong** [comment]
ㅋㅋ 이슈 라벨은 repo 주인만 달 수 있나요? ㅎ.. 붙여보려고 제목 수정했는데 흔적이 남아서 부끄럽네요ㅋㅋㅋㅋ

**Comment by swpark6** [comment]
저만 그런게 아니였네요.. not found method .. 이런식으로 오류가 납니다.

**Comment by ho1234c** [comment]
제가 저번에 #82 에서도 고민한내용인데요, class가아니라 이미 만들어진 객체를 export하면 필요한곳에서 import해서 사용할 수 있습니다. 이 과정에서 노드가 모듈캐싱을하다보니 자동으로 싱글톤 비슷하게 되구요.

https://github.com/gimdongwoo/Dumbledore/blob/a0f452070561dafc59afdeeafd9b8a9f08e601d1/lib/helper/slackBot.js

이런식으로 객체를 리턴해주면 됩니다. 테스트코드가 없다보니 리팩토링과정에서 버그가 발생한것 같네요.

https://github.com/kosslab-kr/Dumbledore/pull/90/commits/3424138278674713e6915fd0d662761f7bb823b8

**Comment by wacilpong** [comment]
@ho1234c 님 고맙습니다! 그런데 slackBot에서 새로운 bot을 만들어서 리턴하면, 이미 만들어진 dumbledore클래스의 slackBot으로 자동으로 연결되는지 혹시 아시나요? 혹은 bot을 여러개 생성하는 셈이 되는 건지 아닌지 모르겠어서요 :0  이부분이 헷갈려서 이도저도 못하고 있었던 것 같습니다ㅠㅠ

**Comment by wacilpong** [comment]
@ho1234c 님 답안해주셔도 됩니다 ㅋㅋ 생각해보니 그럼 dumbledore에서 slackbot을 생성할 필요가 없네요.

**Comment by gimdongwoo** [comment]
parse-server가 동작 후, parse-server에 있는 봇 정보에 따라서 봇을 여러개 운영하는 형태로 가야 하기 때문에,
싱글톤으로 생성되지 않도록 class 문법과 new를 사용하는 형태로 리팩토링 했거든요.
그리고 dumbledore가 slackbot/facebookbot/gitbot등 다양한 봇을 생성해서 인터페이스 해야하니 dumbledore의 constructor에서 인스턴스로 만드는 구조가 맞습니다.

**Comment by swpark6** [comment]
혼란스럽네요, Dumbledore에서 생성된 SlackBot과 replyWithDumbledore 에서 require 되는 SlackBot이 동일한 건가요??

**Comment by gimdongwoo** [comment]
결론적으로 지금은 모듈을 불러서 사용하는 구조가 몽창 잘못되어 있습니다!! 하하하하하

**Comment by gimdongwoo** [comment]
객체지향적 사고로 짜여 있던 코드를 분리하면서 잘못 한것이죠.
이제 다시 바로 잡아야 하구요.

**Comment by gimdongwoo** [comment]
JS에서 call(this, 를 남발하는 코드는 이해하기 어렵고 추적하기 어렵게 만들거든요. 지금이 그런 상태입니다.

이걸 누가 정리해주실분이 나타나주시길 바래요.

**Comment by ho1234c** [comment]
애초에 this의 바인딩 때문에 리팩토링을 한건데, slackbot instance를 Dumbledore의 constructor에서 초기화 하는 구조를 유지해야한다면 현재로선 this를 끌고다니는 문제를 해결할 수가 없겠네요. 그렇다고 처음처럼 한 클래스에 replyWithDumbledore와 bot 호출에 관한 코드를 모두 넣기도 껄끄럽구요. 모듈화와 this를 통한 호출을 둘다 해결할 수 있는 방법을 생각해봐야할것 같습니다.

**Comment by ho1234c** [comment]
@gimdongwoo  parse-server에서 봇을 여러개 운영하는 형태라는건 어떤말씀이신가요?

**Comment by wacilpong** [comment]
그렇다면 parse server에서 봇을 체크해야 한다는 말씀이시죠? 그래서 봇변수를 서버에 저장하려고 시도해보고 있는데 잘 안되네요.. 맞는 방법인지도 의문이고요...ㅠ

**Comment by swpark6** [comment]
완성된 상태라고 가정했을때, 유저 앤드포인트에서 봇 초대 -> Dumbledore에서 봇 생성 후 사용자에게 발급 ...
이런식으로 운영하는게 아닐까요?

**Comment by gimdongwoo** [comment]
@ho1234c Parse-server는 Backend고,
백앤드에 저장된 설정에 따라 dumbledore bot이 여럿 동작하게 되어야 하는 구조이죠.

[class: Bots]
- { name: 'bot1', token: '...', type: 'slack',  ... }
- { name: 'bot2', token: '...', type: 'facebook',  ... }

이렇게 데이터가 parse-server에 저장되어 있다면,
봇을 여러개 띄워야한다는 말이죠.

**Comment by gimdongwoo** [comment]
음... 이 부분은 개발 속도를 위해서 제가 리팩토링 해서 올릴게요.
객체지향적 구조로 인터페이스를 제공하고 그 인터페이스에 따라 분리가 되어야 하는데 지금 controller가 나눠진 상태는 좋지 않습니다.

**Comment by gimdongwoo** [comment]
리팩토링이 되다 만 상태긴 하지만 일단 마무리 하겠습니다.
