### ISSUE TITLE
[question] SQLite -> mongoDB

### ISSUE THREAD

**Issue by wacilpong** [jsdevkr/Dumbledore#97]
```
const Mongo = require('mongodb').MongoClient;
connectDb() {
...
  Mongo.connect("mongodb://localhost/test", (err, db) => {
    if(!err) this.db = db;
  });
}
```

이제 SQLite를 걷어내고 mongoDB로 바꿔야할 것 같은데, mongo와 parse-server 둘다 안써본 저로서는 함께 논의해서 코드를 바꾸는게 좋을 것 같아 이슈 남깁니다. 우선 `dumbledore.js`에서 `connectDb` 함수를 호출할 때 parse-server `databaseURI`로 등록된 db주소를 연결하여 그 db를 `this.db`에 넣으면 될 것 같은데 이렇게 진행해도 될까요?

이후 `raw query`로 된 부분들을 `NoSq`l에 맞게 고치는 작업을 하면 될 것 같은데 어떨까요? parse-server에서 제공하는 다른 방식이 있다면 알려주세요! 열심히 문서를 뒤져도 마땅한 example이 안보여서ㅠ

http://docs.parseplatform.org/parse-server/guide/

**Comment by gimdongwoo** [comment]
parse-server를 도입한 이유는 DB를 걷어내기 위해서 입니다.
요즘에는 백엔드 코드에서 DB를 직접 접근하는 일을 하지 않습니다.
global에 존재하는 Parse 객체를 이용해서 데이터를 CRUD하는 코드로 전부 바꾸면 됩니다.

그런데, 이건 백엔드 쪽의 @ zx6658 님도 봐주셔야 합니다.

**Comment by gimdongwoo** [comment]
parse-server를 도입한 이유는 DB를 걷어내기 위해서 입니다.
요즘에는 백엔드 코드에서 DB를 직접 접근하는 일을 하지 않습니다.
global에 존재하는 Parse 객체를 이용해서 데이터를 CRUD하는 코드로 전부 바꾸면 됩니다.

그런데, 이건 백엔드 쪽의 @zx6658 이승규 님도 봐주셔야 합니다.

**Comment by HyeonUkCho** [comment]
bot.js에서 parse instance를 만들어서 이미 Mongo가 포함되어 있는 것 같습니다.

**Comment by gimdongwoo** [comment]
MongoDB는 잊으세요. DB를 잊으세요!! 제발 ㅋㅋㅋ

**Comment by HyeonUkCho** [comment]
넵넵 ㅎㅎㅎㅎ

**Comment by wacilpong** [comment]
아 이해했습니다 ㅋㅋㅋㅋㅋ

**Comment by wacilpong** [comment]
그럼 http://docs.parseplatform.org/parse-server/guide/ 에서 LiveQuery부분을 참고하면 될까요? `Parse.Query`가 parse의 주요 컨셉이라고 나와있는데, 이를 사용하여 CRUD로 바꾸면 된다는 말씀이시죠?

**Comment by HyeonUkCho** [comment]
http://docs.parseplatform.org/js/guide/
여기 참고하시면 좋을듯 합니다

**Comment by wacilpong** [comment]
@HyeonwookCho 앗 그부분은 parse javascript SDK라서.. 우리쪽에서 parse-server를 올려놓았기 때문에 그 백엔드에서 CRUD를 다루는 부분에 대한 reference를 여쭤본 거였습니다. ㅎㅎ

**Comment by HyeonUkCho** [comment]
아항ㅎㅎㅎ넵넵

**Comment by wacilpong** [comment]
우선 생성된 Parse 객체로 어떻게 쿼리를 다루는지 공부해야겠습니다...! 모르는 것 투성이라 질문을 너무 자주 한 것 같아 죄송합니다ㅠ

**Comment by wacilpong** [comment]
https://designingforscale.com/query-on-a-parse-pointer/

**Comment by ho1234c** [comment]
그냥 SDK에 나와있는대로 orm쓰듯이 쿼리보내면 되는거같아보여요!

**Comment by ho1234c** [comment]
아 그런데 그냥 쿼리 말고도 웹소켓 기반으로서 리얼타임 db같이 이벤트기반으로 뭔가 만들수있는 Live Query라는 걸 추가로 제공하는것같네요

**Comment by wacilpong** [comment]
@ho1234c 네 그래서 그부분에 대해 일단 짬짬히 공부중입니다..!
https://github.com/parse-community/parse-server-example/blob/master/index.js

**Comment by Brew-Brew** [comment]
저그러면 궁금한게 있는데, 그럼 현재코드는 parse server랑 연결은 되어있는 상황이지만, 컨트롤러에 있는
 db쿼리문들을 parse객체로 옮겨서(?) parsr객체로 쿼리를 다뤄주는 방식으로 코드를 바꾸는 작업이 진행되어야 하는건가요?? ㅠㅠ

**Comment by Brew-Brew** [comment]
그리고 저런 대시보드가 있던데, 저기에 나온 데이터들을 활용해서 데이터들을 가공하거나, 축적하면 되는것일까요? ㅠㅠ...
![image](https://user-images.githubusercontent.com/26598542/31820621-275539fa-b5dd-11e7-8a03-6babdc4b652c.png)

**Comment by gimdongwoo** [comment]
네. 우선은 백앤드 코드에서 DB를 걷어내구요.
Parse js sdk를 이용해서 parse-server에 데이터가 저장되게 변경하면 됩니다.
http://docs.parseplatform.org/js/guide/

이것이 백앤드팀에서 첫번째로 해야 할 일이죠 🥇

**Comment by Brew-Brew** [comment]
아하...넵.. 많이 여쭙겠씁니다 ㅠ
