### ISSUE TITLE
[질문] cannot find module 오류

### ISSUE THREAD

**Issue by Brew-Brew** [jsdevkr/Dumbledore#99]
![image](https://user-images.githubusercontent.com/26598542/31817542-6c8c7be0-b5cf-11e7-870f-6f7959327f45.png)
 어제 시험이 끝나서 부랴부랴 이제 열심히 다시 페치해서 제 로컬로 가져와서 해보고있는데욥!!!ㅠㅠㅠㅠ 이것저것 추가된것도 많아서 찬찬히 보고있는데,  npm run dev를 했을때, 이런 에러가 뜨는데 아래 이슈에서 말씀해주신것 처럼 parse sever(?)라는것을 통해 그쪽으로 디비쿼리를 옮겨서 작업을 하는 형태?? 가 맞는것인가요 그렇다면 sqlite는 사용하지 않는것이면 저 에러는 안뜨는게 맞지않나용? ㅠㅠㅠㅠ 모르는게투성이라 ㅠㅠㅠㅠ 질문드립니다.

**Comment by Brew-Brew** [comment]
몽고 db는 그럼 사용하지 않는것인가요 ㅠㅠ.... npm run dev 명령어로 시작할때는 뜨던데 ㅠㅠㅠㅠ

**Comment by ho1234c** [comment]
항상 dependency가 바뀔 수 있으니 fetch후엔 npm install을 해주세요.

**Comment by Brew-Brew** [comment]
네네 안그래도 npm install을 했는데도 저런 오류가 떠서요 ㅠㅠ

**Comment by ho1234c** [comment]
음.. 머지도 제대로 되셨나요?

**Comment by Brew-Brew** [comment]
네네 ㅠㅠㅠ 근데 소스트리에서 merge나 push할때 오류가 나는경우도 있나요ㅠㅠ 하다가 팅기긴했었거든요 ㅠㅠ 
![image](https://user-images.githubusercontent.com/26598542/31818142-c48e4b82-b5d1-11e7-8694-a51156e28977.png)
이런식으로 나오는거 보니 원래코드와 비교해 package파일이 뭔가 잘못된거 같긴하네요 ㅠㅠ

**Comment by ho1234c** [comment]
일단 지금 sqlite3를 걷어낸 상태는 아니에요. 이제 해야하는작업이죠. 그리고 저것만 봐서는 이상이 없어요! 우선 혹시 의존성이 깨졌을 수 있으니 node_modules폴더 삭제하고 다시 npm i 해보시겠어요?

**Comment by Brew-Brew** [comment]
지우고 어찌저찌 파일 수정하다보니 됬네요 ㅋㅋㅋㅋ 감사합니다 ㅠ 맥주한잔 대접하고싶네요 ㅎ근데 npm i 랑 npm install의 차이가 있나용? ㅎㅎ... 너무 멍청한 질문인가요 헤헤..

**Comment by ho1234c** [comment]
@zx6658 같아요~ alias입니다.
